### ISSUE TITLE
Remove dependency on request

### ISSUE THREAD

**Issue by dorward** [Niels-IO/next-image-export-optimizer#107]
next-image-export-optimizer depends on request, which is deprecated and in turn depends on har-validator (no longer supported), uuid 3.4 (which has known problems and recommends using v7 or higher).

Please replace request with fetch (if you don't mind on insisting on a very recent Node.js), node:http, node-fetch, or similar.

**Comment by Niels-IO** [comment]
Thank you for the hint! I replaced request in PR #108

**Comment by dorward** [comment]
Fab! Thanks.
