### ISSUE TITLE
Package size - sha.js

### ISSUE THREAD

**Issue by PeterKottas** [Niels-IO/next-image-export-optimizer#109]
I noticed a runtime dependency to sha.js was added as part of https://github.com/Niels-IO/next-image-export-optimizer/commit/e3e8273cf26aa7093e8cc8edb49ad2cf503960f7

As a result, the lib went from [1.3kb (gzipped) to 5.8kb. Something like 450% the size](https://bundlephobia.com/package/next-image-export-optimizer@1.3.0). I wonder 2 things
a) Can we avoid using it? It seems like sha256 should be included in modern browsers without using the lib [source](https://stackoverflow.com/questions/59777670/how-can-i-hash-a-string-with-sha256-in-js) 
b) If not, can we at least make sure to only include the 256 as that appears to be the only one that we are using? 

If we go down the browser API route, we need to make sure it works with SSR too. The modern way to do this:

```
async function sha256(text: string): Promise<string> {
  const textAsBuffer = new TextEncoder().encode(text);
  const hashBuffer = await window.crypto.subtle.digest('SHA-256', textAsBuffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  const digest = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
  return digest;
}
```

Would obviously fail on server.

Many thanks @NielsApp !

**Comment by PeterKottas** [comment]
Afk maybe an util like this? But I am not sure if webpack is smart enough to not include this in client bundle.

```
async function sha256(text: string): Promise<string> {
  const textAsBuffer = new TextEncoder().encode(text);
  const hashBuffer = await (typeof window !== 'undefined'
    ? window.crypto
    : require("crypto")
  ).subtle.digest("SHA-256", textAsBuffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  const digest = hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
  return digest;
}
```

**Comment by Niels-IO** [comment]
Hi @PeterKottas,

Good point! I wasn't too happy with the dependency either. A tad more unfancy, but a good enough solution is only to encode the URL. I made the change in #110 

Do you agree?

**Comment by PeterKottas** [comment]
I think that does it! Seeing that the hash was calculated from the source, not from the content, this is pretty much equivalent. Might even be preferable, as this way, you at least have some control over the downloaded image name. (if somebody right-click save the image). I say good!
