### ISSUE TITLE
Setting placeholder from "empty" to lowest possible image size of optimised images 

### ISSUE THREAD

**Issue by ueberf** [Niels-IO/next-image-export-optimizer#11]
One nice thing about the Next.js Image component is the [placeholder functionality](https://nextjs.org/docs/api-reference/next/image#placeholder), but it requires a `blurDataURL` to use for the blur effect.

Of course it would be an option to assume that the optimised images will be at the specific location, and add the `blurDataURL` with something like this:

```
const image = '/example.jpg'
const imageName = 'example'

<ExportedImage
    src= { image } // "image.jpg"
    alt="Large Image"
    width='720'
    height='960'
    layout='responsive'
    placeholder="blur"
    blurDataURL= {`/nextImageExportOptimizer/${imageName}-opt-16.WEBP`} // "/nextImageExportOptimizer/example-opt-16.WEBP"
/> 
```

However, this can become tedious if you have to provide both the full image path for the `src` and the image file name (to not end up with a broken path like `/nextImageExportOptimizer/example.jpg-opt-16.WEBP`), or include extra script to automatically strip the file ending from the image. 

Is there an easier way to add the URL (let's say `example-opt-16.WEBP`) to each `<ExportedImage />` component that has the property `placeholder="blur"`?

Thanks!

**Comment by Niels-IO** [comment]
Hi @ueberf,

Awesome suggestion! I coded it up, and you can have a look at the code in the PR #13. 

Do you have a recommendation about the width we should choose for the blur image? I think the images with 32px width would maybe look better than the ones with 16px width and still be sufficiently small?

Cheers
Niels

**Comment by lgn-lvx3** [comment]
Just to comment on this, I know I'm not involved but the docs say 'less than a 10x10' is ideal, because its enlarged. Check it out - https://nextjs.org/docs/api-reference/next/image#blurdataurl

**Comment by Niels-IO** [comment]
Hi @lgn-lvx3,

Thanks for the hint! I think they would know best, so I adapted the Pull Request #13 to have a dedicated config variable for automatic generated blur images. When the variable _generateAndUseBlurImages_ is true, it generates an additional image with a width of 10px and uses it in the ExportedImage component.

**Comment by Perni1984** [comment]
Hey @Niels-IO we think this is a great addition to your package, is there any reason you did not merge it yet? And if so, can we support on getting any eventual blockers out of the way?

**Comment by Niels-IO** [comment]
Hi @Perni1984,
I just finished the merge in PR #13 and published a new version. There was no particular reason for the delay 🙂
If you like, you can test the new release and let me know if everything works as expected.
