### ISSUE TITLE
Return promise from remoteOptimizedImages.js

### ISSUE THREAD

**Issue by PeterKottas** [Niels-IO/next-image-export-optimizer#112]
RemoteOptimizedImages.js could optionally return a promise that resolves to an array of remote images. 

TLDR: I reckon there will be people (other than me) who will fetch these from cms or some different location. Allowing the file to return a promise would allow this functionality. 

@Niels-IO Do you want me to PR this or is it easier for you? I am good either way.

**Comment by Niels-IO** [comment]
Hi @PeterKottas,

Go ahead with the PR! Thanks

**Comment by PeterKottas** [comment]
Done in #113 , please double-check as I was unable to run tests. Further details in PR.
