### ISSUE TITLE
Only generate images that will be used

### ISSUE THREAD

**Issue by Lastofthefirst** [Niels-IO/next-image-export-optimizer#116]
Would it be possible to determine which sized images will be used for a given image and only generate those?

Love using this btw, its a huge advantage to  my workflow thank you!

**Comment by Niels-IO** [comment]
Hi @Lastofthefirst 

Unfortunately currently not. The front end image component and the image optimisation at export time are quite independent. To make it work you would have to keep a list of the used sizes somewhere or dynamically go through the whole project and extract the used sizes for each image.

**Comment by Lastofthefirst** [comment]
Alright. Thanks.
