### ISSUE TITLE
Adjusting deviceSizes breaks srcSet 

### ISSUE THREAD

**Issue by ueberf** [Niels-IO/next-image-export-optimizer#12]
I ran into an issue when trying to adjust the image and device sizes in `next.config.js`.

For my specific use case I do not need all default `imageSizes: [16, 32, 48, 64, 96, 128, 256, 384]` and `deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840]`, and as a way to speed up the build time tried to adjust the list of sizes to something more suitable, like `deviceSizes: [640, 750, 1080, 1920]`.

It might also be that I do not understand the configuration properly. However, if they are not meant to be customised, then I also do not see the need to specify them in `next.config.js`🙂 

### Expected behaviour 
The plugin only generates new, optimised images for the specified `imageSizes` and `deviceSizes`, and adjusts the `srcSet` of the image tag to make use of the new sizes.

### Observed behaviour
The plugin indeed only generated the sizes specified, but does not adjust the image tag properly so that it includes non-existent files. This breaks the image when the browser window gets too wide or too small.

![image](https://user-images.githubusercontent.com/19748898/163681846-f9b98161-70d5-43fc-aadd-0becffe3477a.png)

![image](https://user-images.githubusercontent.com/19748898/163681793-e5e0daec-c3a8-4f3c-a0b7-fad078c20991.png)

--- 

### Ways to reproduce the bug

**1. Change next.config.js**
```
module.exports = {
  images: {
    loader: "custom",
    nextImageExportOptimizer: {
      imageFolderPath: "public/images",
      exportFolderPath: "out",
      imageSizes: [16, 32],
      deviceSizes: [1920, 2048],
      quality: 75,
    },
  },
  env: {
    storePicturesInWEBP: true,
  },
};
```

**2. Run `npm run export`**
**3. Resulting `out/images` folder** 
<img width="556" alt="image" src="https://user-images.githubusercontent.com/19748898/163681714-9f15deb5-e786-4f5a-8afd-2e071184a5b0.png">

**4. Resulting img tag**
```
<img id="test_image" alt="test_image" sizes="100vw" 
srcset="images/nextImageExportOptimizer/chris-zhang-Jq8-3Bmh1pQ-unsplash-opt-640.WEBP 640w,
images/nextImageExportOptimizer/chris-zhang-Jq8-3Bmh1pQ-unsplash-opt-750.WEBP 750w,
images/nextImageExportOptimizer/chris-zhang-Jq8-3Bmh1pQ-unsplash-opt-828.WEBP 828w,
images/nextImageExportOptimizer/chris-zhang-Jq8-3Bmh1pQ-unsplash-opt-1080.WEBP 1080w,
images/nextImageExportOptimizer/chris-zhang-Jq8-3Bmh1pQ-unsplash-opt-1200.WEBP 1200w,
images/nextImageExportOptimizer/chris-zhang-Jq8-3Bmh1pQ-unsplash-opt-1920.WEBP 1920w,
images/nextImageExportOptimizer/chris-zhang-Jq8-3Bmh1pQ-unsplash-opt-2048.WEBP 2048w,
images/nextImageExportOptimizer/chris-zhang-Jq8-3Bmh1pQ-unsplash-opt-3840.WEBP 3840w" 
src="images/nextImageExportOptimizer/chris-zhang-Jq8-3Bmh1pQ-unsplash-opt-3840.WEBP" 
decoding="async" data-nimg="fill" style="position: absolute; inset: 0px; box-sizing: border-box; padding: 0px; border: none; margin: auto; display: block; width: 0px; height: 0px; min-width: 100%; max-width: 100%; min-height: 100%; max-height: 100%; object-fit: cover;">
```

**Comment by Niels-IO** [comment]
Hi @ueberf,

Thanks so much for noticing this bug. I made a mistake in the specification of the configuration keys **imageSize** and **deviceSizes** in the next.config.js.

The change should be the following so that Next.js automatically takes the keys and thus the widths into account when it generates the srcset for the image:

```diff
{
// next.config.js
module.exports = {
  images: {
    loader: "custom",
 imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
 deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    nextImageExportOptimizer: {
      imageFolderPath: "public/images",
      exportFolderPath: "out",
-      imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
-     deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
      quality: 75,
    },
  },
  env: {
    storePicturesInWEBP: true,
  },
};
}
```

I will update the README to reflect the correct set-up.

**Comment by Niels-IO** [comment]
Hey @ueberf,

Could you please confirm that v0.9.4 fixes the problem also on your side? (You have to change the nextjs.config.js keys yourself, as the library cannot change it)

Thanks a lot!!

**Comment by ueberf** [comment]
Hey @Niels-IO,

Yes, that fixed the issue and the `srcset` adapts to the exported images now!

One thing that I do not understand 100% yet is why the specified imageSizes do not appear in the `srcset`, too.
If they do not get included, what is the point of generating them?

Thanks for all you work!!

**Comment by Niels-IO** [comment]
Hey @ueberf,
Cool! Regarding the image sizes I found this in the docs:
https://nextjs.org/docs/api-reference/next/image#image-sizes

> The reason there are two separate lists is that imageSizes is only used for images which provide a [sizes](https://nextjs.org/docs/api-reference/next/image#sizes) prop, which indicates that the image is less than the full width of the screen.

I will have to test it the complete srcset will be generate with the sizes prop.

**Comment by ueberf** [comment]
I did a little test by adding another image in the example [pages/ index.js ](https://github.com/Niels-IO/next-image-export-optimizer/blob/master/example/pages/index.js), giving it a parent with `display: "block"` based on [next/image documentation](https://nextjs.org/docs/api-reference/next/image#layout)  and setting some custom `imageSizes` & `deviceSizes`

```
{/* Added Image Element */}
<div style={{display: "block", width: "100px"}}>
  <ExportedImage
    src="images/subfolder/subfolder2/ollie-barker-jones-K52HVSPVvKI-unsplash.jpg"
    layout="responsive"
    width={400}
    height={600}
    alt="Responsive image"
  />
</div>
```

```
module.exports = {
  images: {
    loader: "custom",
    imageSizes: [16, 32],
    deviceSizes: [1920, 2048],
    nextImageExportOptimizer: {
      imageFolderPath: "public/images",
      exportFolderPath: "out",  
      quality: 75,
    },
  },
  env: {
    storePicturesInWEBP: true,
  },
};
```

---

Images get optimised as WEBP in the four specified `imageSizes` and `deviceSizes`, but are not listed in the `srcSet`

The resulting `img` looks like this:
```
<img 
alt="Fixed image" 
src="images/subfolder/subfolder2/nextImageExportOptimizer/ollie-barker-jones-K52HVSPVvKI-unsplash-opt-2048.WEBP"
decoding="async"  data-nimg="responsive" 
style="position: absolute; inset: 0px; box-sizing: border-box; padding: 0px; border: none; margin: auto; display: block; width: 0px; height: 0px; min-width: 100%; max-width: 100%; min-height: 100%; max-height: 100%;" sizes="100vw"
srcset=" images/subfolder/subfolder2/nextImageExportOptimizer/ollie-barker-jones-K52HVSPVvKI-unsplash-opt-1920.WEBP 1920w, images/subfolder/subfolder2/nextImageExportOptimizer/ollie-barker-jones-K52HVSPVvKI-unsplash-opt-2048.WEBP 2048w"
>

```

At least based on this test it does not seem like the `imageSizes` are taken into consideration?

**Comment by Niels-IO** [comment]
Hi @ueberf,

According to the documentation, the Nextjs image component will use the imageSizes array on one of the following conditions:

- The Image component has a fixed layout with specified width and height, like this:
   ```
   <ExportedImage
     src="images/chris-zhang-Jq8-3Bmh1pQ-unsplash.jpg"
     layout="fixed"
     width="100px"
     height="100px"
     objectFit="cover"
     priority={true}
     alt="test_image"
   />
   ```
- The Image component has a sizes prop with media queries like this for example:
   ```
   sizes="(min-width: 1024px) 48px, (min-width: 475px) 32px, 16px"
   ```

I tested it for the first condition, and it does indeed use the imageSizes array to generate the srcset. I added some tests in the pull request #17 if you want to have a deeper look.

**Comment by ueberf** [comment]
Hey @Niels-IO,

Thanks for the heads-up! 
Seems like I haven't read the Next's image documentation properly enough, but then it is indeed working as intended.
