### ISSUE TITLE
issue with Node < 16

### ISSUE THREAD

**Issue by kinotto** [Niels-IO/next-image-export-optimizer#132]
Hi there,
this library looks really useful, 
i was just wondering if it works with Node < 16.0
i'm using v14.2 and i'm getting this error when i try to install it

![image](https://user-images.githubusercontent.com/4570071/229796465-0cb919df-88c3-42e7-814d-c19a59ee2abb.png)

Thanks

**Comment by Niels-IO** [comment]
Hi @kinotto 
I tried for the last hour to get node 14 to work, but couldn't. If you do a fork and work on the integration, I can accept a PR.
