### ISSUE TITLE
Support ref for ExportedImage component

### ISSUE THREAD

**Issue by tnvinh00** [Niels-IO/next-image-export-optimizer#135]
Hi @Niels-IO 

Currently, this package does not support [ref](https://react.dev/reference/react/forwardRef) for component ExportedImage.
How can I use ref for this component?

**Comment by Niels-IO** [comment]
Hi @tnvinh00,

I created #136 for this functionality.

**Comment by tnvinh00** [comment]
Thank you, it's very useful.
