### ISSUE TITLE
Converted animated images lose animation

### ISSUE THREAD

**Issue by bryanjtc** [Niels-IO/next-image-export-optimizer#138]
Adding the animated option to sharp fixes this issue.
Ex:
```
sharp(input.gif, { animated: true }).image.webp()
```

**Comment by bryanjtc** [comment]
It seems the options it's already enabled.
I keep having the issue on the mobile version of the website that I created using next-image-export-optimizet

**Comment by Niels-IO** [comment]
Hi @bryanjtc, Could you provide more information? The GIFS on my mobile phone do work. Which browser are you using and could you maybe provide the link or the image to debug the issue?

**Comment by Niels-IO** [comment]
Cannot fix without the support of bug reporter

**Comment by bryanjtc** [comment]
Checking in. I had an old version of the dependency. After updating, it worked.
