### ISSUE TITLE
module is not defined in ES module scope

### ISSUE THREAD

**Issue by chaveamin** [Niels-IO/next-image-export-optimizer#139]
This error occurs when running dev server: `module is not defined in ES module scope`
![img](https://user-images.githubusercontent.com/78597787/235844402-e5b7a933-7a98-49dc-a7b4-ed08717a2483.jpg)

**Comment by Niels-IO** [comment]
Hi @chaveamin, change the filename next.config.mjs to next.config.js.

**Comment by chaveamin** [comment]
I did it before(with .js and .cjs) but it shows the same error
with .js:
![1](https://user-images.githubusercontent.com/78597787/235858788-6c673dfb-08da-4f4b-b178-90f91b96c111.jpg)
with .cjs
![2](https://user-images.githubusercontent.com/78597787/235858838-30e11a3b-7eab-4982-af7d-33e8df005ca2.jpg)

**Comment by Niels-IO** [comment]
I am quite sure this is not an issue with next-image-export-optimizer. Try to comment out on a first try the imports in your next.config.js and if the error persists, everything that comes from next-image-export-optimizer.

**Comment by chaveamin** [comment]
Problem solved by deleting the library completely and reinstalling it again, Thanks
