### ISSUE TITLE
Next config env should be string, not json value

### ISSUE THREAD

**Issue by zifeo** [Niels-IO/next-image-export-optimizer#140]
When type checking the config with `/** @type {import('next').NextConfig} */`, the env variables like `nextImageExportOptimizer_quality` should be strings.

**Comment by Niels-IO** [comment]
Hi @zifeo,

Thanks, I changed this in this PR #141

**Comment by zifeo** [comment]
@Niels-IO That was fast, thanks! 🙌

**Comment by zifeo** [comment]
@Niels-IO just tried with the latest version and `nextImageExportOptimizer_quality` still require number and the readme may need to be updated as well
