### ISSUE TITLE
Is there a clean way to not use imageSizes/deviceSizes at all?

### ISSUE THREAD

**Issue by metalmarker** [Niels-IO/next-image-export-optimizer#151]
In my use case, I'm looking to only use the WebP format, without scaling down image sizes based on device sizes.

The hack I'm using is to specify `imageSizes: [3840], deviceSizes: [512]` to ensure that my (smaller than 512 px) images are not scaled down, but interested to know there's a "cleaner" way to achieve this outcome. Thanks!

**Comment by Niels-IO** [comment]
Hi @metalmarker,

I think you found the cleanest way to do it with this package. I wouldn't support this particular use case because the primary purpose is image optimization. Sorry about this!
