### ISSUE TITLE
nextImageExportOptimizer still exists after setting of custom folder 

### ISSUE THREAD

**Issue by rtatarinov** [Niels-IO/next-image-export-optimizer#156]
Hello! First of all, thank a lot for your package. I use it, and it's wonderful. However, when I set the custom image folder the `next-image-export-optimizer` continue to create `nextImageExportOptimizer` folder aside my `optimized` folder. My config is:
```
images: {
    loader: "custom",
  },
  transpilePackages: ["next-image-export-optimizer"],
  env: {
    nextImageExportOptimizer_imageFolderPath: "public/images",
    nextImageExportOptimizer_exportFolderPath: "out",
    nextImageExportOptimizer_quality: 85,
    nextImageExportOptimizer_storePicturesInWEBP: true,
    nextImageExportOptimizer_exportFolderName: "optimized",
  },
  ```
And I see two folder after export `nextImageExportOptimizer` and `optimized`. I think it's too much. Can the package doesn't create a `nextImageExportOptimizer` folder aside with custom folder?

**Comment by Niels-IO** [comment]
Hi @rtatarinov,

I just re-tested the behavior of the nextImageExportOptimizer_exportFolderName variable and it does not create folders with the old name but it also does not delete already created folders with the previous name as expected. Maybe delete the old folders and they should not be generated again.

**Comment by rtatarinov** [comment]
Yes, thank you
