### ISSUE TITLE
Error 'NextRouter was not mounted' occurs when building with SSG after updating from v1.7.0 to v1.8.0

### ISSUE THREAD

**Issue by NPJigaK** [Niels-IO/next-image-export-optimizer#157]
After updating from v1.7.0 to v1.8.0, I encountered an error 'NextRouter was not mounted' when building with Static Site Generation (SSG). I believe this issue stems from changes made to [use useRouter](https://github.com/Niels-IO/next-image-export-optimizer/compare/v1.7.0...v1.8.0#diff-cbaf62eea704afafc5d631d332317f795ed1640b560bb15680466010cac0b2ebR5). Was this an intentional change? Does this mean SSG is no longer supported?

I've been a fan of this module for its ability to optimize images even with SSG. I would like to continue using it beyond v1.8.0. 
I understand that resolving this issue might take some time and effort, but I would greatly appreciate your assistance. 
Thank you.

**Comment by zifeo** [comment]
Also facing this [issue](https://github.com/Niels-IO/next-image-export-optimizer/pull/155/files#diff-cbaf62eea704afafc5d631d332317f795ed1640b560bb15680466010cac0b2ebR5).

**Comment by armandoborge** [comment]
@NPJigaK, did you find a solution to this? 
I am facing the same issue; no idea what's going on!

**Comment by Niels-IO** [comment]
Hi @NPJigaK Thanks for reporting this issue. I fixed it now and got rid of the useRouter. To use the basePath, you now have to pass it as a prop to the ExportedImage.

**Comment by NPJigaK** [comment]
@Niels-IO 
I greatly appreciate your swift and efficient response. I am sincerely looking forward to seeing this library evolve and improve.
Thank you once again.
