### ISSUE TITLE
Support quality property

### ISSUE THREAD

**Issue by inquiztr** [Niels-IO/next-image-export-optimizer#171]
Nextsj image component allows to define a quality setting. In my case the default is 75, but I am trying to overide for an image i will be using as a background image that could use a higher quality setting.
However passing in a Quality parameter to ExportedImage is causing a complaint during build and linting.

```
<ExportedImage
    src={bg}
    alt=""
    className={styles.heroBG}
    fill={true}
    sizes="100vw"
    placeholder="blur"
    priority={true}
    quality="90"
    style={{ objectFit: 'cover' }}
/>
```

**Comment by Niels-IO** [comment]
Hi @inquiztr,

The error comes up purposefully as this library cannot support the quality property on an per-image basis.

In order for it to be possible, the library would have to scan all code files of the project to look for which image uses which quality property (if any). 

Cheers,
Niels

**Comment by inquiztr** [comment]
@Niels-IO thank you for the feedback. I appreciate your efforts and this library. 
I think there should be some mention in the documentation as I just assumed all image component properties were supported as you mention your library wraps the Image component.
I also see the document mentions using layout="responsive" property but I believe as of Next13 layout property has been removed.

**Comment by Niels-IO** [comment]
Hi @inquiztr,

Thank you very much for the comments. I adapted the README to state the issue around the quality prop.
