### ISSUE TITLE
Full width Image issue.

### ISSUE THREAD

**Issue by EnderGnar** [Niels-IO/next-image-export-optimizer#178]
There is a new pattern needed when using an `<Image>` with non pixel defined width. It would look something like this:
```
<Image
  src="url"
  width={0}
  height={0}
  sizes="100vw"
  style={{ width: '100%', height: 'auto' }} // optional
/>
```
from https://github.com/vercel/next.js/discussions/18474#discussioncomment-5501724.

In debug mode this does not work because width is not defined, maybe some undefined checks that are a little to weak.

**Comment by Niels-IO** [comment]
Hi @EnderGnar,

The solution to a full-with image without a specified width value is to use the [fill](https://nextjs.org/docs/pages/api-reference/components/image#fill) property. 

> A boolean that causes the image to fill the parent element, which is useful when the [width](https://nextjs.org/docs/pages/api-reference/components/image#width) and [height](https://nextjs.org/docs/pages/api-reference/components/image#height) are unknown.
> The parent element must assign position: "relative", position: "fixed", or position: "absolute" style.

Then you can give the parent a width:100% or whatever may be suitable in the specific situation.

Your quoted solution seem like a hack that should not be encouraged.

**Comment by EnderGnar** [comment]
Oh wow sorry should have just searched a little bit further in that thread.

Thank you :)
