### ISSUE TITLE
Images that dont have predefined height

### ISSUE THREAD

**Issue by joebentaylor1995** [Niels-IO/next-image-export-optimizer#192]
What props to do you use if your image has a rough width estimate, responsively, but needs to be auto in height?

Cant use fill, as that fills the parent div, cant use set height as that will change responsively...

**Comment by Niels-IO** [comment]
Hi @joebentaylor1995,

would this work? https://nextjs.org/docs/pages/api-reference/components/image#responsive-image-with-aspect-ratio

Otherwise, can you wrap it with another div with your appropriate dimensioning so that you can use `fill`? (as that is the intended approach by Next.js)

**Comment by joebentaylor1995** [comment]
Unfortunately not as the image will be supplied from the CMS and would be different ratios as and when the client changes the imageKind regards,JoeOn 20 Dec 2023, at 16:54, Niels ***@***.***> wrote:﻿
Hi @joebentaylor1995,
would this work? https://nextjs.org/docs/pages/api-reference/components/image#responsive-image-with-aspect-ratio
Otherwise, can you wrap it with another div with your appropriate dimensioning so that you can use fill? (as that is the intended approach by Next.js)

**Comment by joebentaylor1995** [comment]
GatsbyJS image worked perfectly for this scenario

**Comment by Niels-IO** [comment]
How would you define the Next.js image component in a normal next.js application?

**Comment by joebentaylor1995** [comment]
I’m not sure, I’m new to next and it’s one of the biggest disappointments for images I’ve ever seenKind regards,JoeOn 21 Dec 2023, at 14:41, Niels ***@***.***> wrote:﻿
How would you define the Next.js image component in a normal next.js application?

**Comment by Niels-IO** [comment]
I think the best bet would be to wrap your image in another div and use the Next.js image component as it is intended.

**Comment by joebentaylor1995** [comment]
Oh, that sucks.Can’t you just make the height allow “auto”Kind regards,JoeOn 21 Dec 2023, at 16:23, Niels ***@***.***> wrote:﻿
I think the best bet would be to wrap your image in another div and use the Next.js image component as it is intended.

**Comment by joebentaylor1995** [comment]
The fact this is closed is such a poor way to deal with a request.
