### ISSUE TITLE
Can't optimize two different path

### ISSUE THREAD

**Issue by chaveamin** [Niels-IO/next-image-export-optimizer#196]
I have 2 main directories for my Images `public/products` & `src/images` Considering that the package can't specify two directory. `src/images`  folder won't be optimized and can't be found by browser.
![Screenshot 2024-01-07 193827](https://github.com/Niels-IO/next-image-export-optimizer/assets/78597787/3a0bb1cc-1b18-48f9-a7c5-f6517eaa6083)

**Comment by Niels-IO** [comment]
You can statically import images that reside outside of the specified image folder. That will solve this problem.
