### ISSUE TITLE
unexpected property: transpilePackages

### ISSUE THREAD

**Issue by benlutz** [Niels-IO/next-image-export-optimizer#197]
Hey there,

I installed the packages as described in the README, and so far everything is working as expected. Starting up the dev server, however, I get this warning:

```
Invalid next.config.js options detected: 
  - The root value has an unexpected property, transpilePackages, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
```

Is this expected?

**Comment by el-j** [comment]
what version of nextjs do you use?
before [13.0.0](https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages)? 
if so and u cannot upgrade u may use this:
https://www.npmjs.com/package/next-transpile-modules
?

**Comment by Niels-IO** [comment]
@benlutz, can you confirm on which version of Next.js you are?

**Comment by benlutz** [comment]
I'm using 13!

**Comment by Niels-IO** [comment]
What happens when you remove the property "transpilePackages" from the next.config.js?
