### ISSUE TITLE
Srcset not created for Static Images

### ISSUE THREAD

**Issue by el-j** [Niels-IO/next-image-export-optimizer#198]
Hej i really love the idea of this package. 

anyways sadly just get one 1x and 2x srcset attribute both for the biggest version of my image.
it does not load smaller versions on smaller screensizes. 

i am wondering if it is because of how i use the static images?
as i have them all in my public folder and i do not want to hand in any width or height parameters 
as u show in the example:
![image](https://github.com/Niels-IO/next-image-export-optimizer/assets/2795534/9ab136d7-52d8-4d4f-bbfe-0a611e328782)

i tried to trick this importing a bit by importing all my images into the header of an "Images.tsx" and later choose them 
from the image-src i get into the component. i hand this then to src of `ExportedImage` component.

```tsx
import staticimage from  "../public/staticiamage.png"
import staticimage2 from  "../public/staticiamage2.png"

const images = { staticimage, staticimage2 } as { [key: string]: StaticImageData };

export const Images = ({
src
}: {
  src: string;
}) => {
  let theImage = images[src];
  return (
    <ExportedImage
      src={theImage}
      alt={src}
      loading="lazy"
      basePath={
        process.env.NEXT_PUBLIC_BASE_PATH
          ? process.env.NEXT_PUBLIC_BASE_PATH
          : ""
      }
    />
  );
};
```

the output is then e.g.
```html
<img alt="staticimage" 
loading="lazy" 
width="1920" 
height="1080" 
decoding="async" 
data-nimg="1" 
srcset="/nextImageExportOptimizer/staticimage.a31d2aae-opt-1920.WEBP 1x,
 /nextImageExportOptimizer/staticimage.a31d2aae-opt-1920.WEBP 2x" 
src="http://localhost:3000/nextImageExportOptimizer/staticimage.a31d2aae-opt-1920.WEBP" 
style="color: transparent;" >
```
when i load i get in source first a load of the smallest variant (like: opt-10.WEBP) then i load the biggest version. the other versions are all created from the export command, but they are not mentioned in the srcset attribute in the html.

do you have any clue how i can get a nice srcset from my images?

**Comment by el-j** [comment]
any help would be much appreciated as i want to put the page online but suffering form this problem a lot. maybe i do anything wrong? from you working online example i saw that, the width and height of the container and the width and height of the image is changed when dragging the slider. 

so does it mean i need a width and height in px on container and image? then i got the idea of this package wrong, maybe?

**Comment by Niels-IO** [comment]
Hi @el-j,

I tested your setup in the example app in this repository. It works and I get all the different sizes in the srcset. Can you create a minimal reproduction so that I can debug it? 

When you use the staticically imported images, you do not have to specify any width or height.

**Comment by terijaki** [comment]
I'm having the same problem (https://github.com/terijaki/vcmuellheim)

Optimized Images are generated fine with **next dev** but are not present with **next build && next-image-export-optimizer**

Note: I'm not using && next export since this is deprecated in Next14 and cause build failures: https://nextjs.org/docs/advanced-features/static-html-export

**Comment by Niels-IO** [comment]
@terijaki Can you point me to a specific code section of your repo where it doesn't work?

**Comment by terijaki** [comment]
@Niels-IO ofc

- https://github.com/terijaki/vcmuellheim/blob/main/app/%5Bpostorpage%5D/page.tsx (see line 150 at the very end)
- this part is handling the dynamic blog post. example:
  - https://vcmuellheim.de/2024-01-19-5-spieltag-der-saison-fur-damen-i
  - the images are stored in public/images/blog/[year]/[month]/[day] : https://github.com/terijaki/vcmuellheim/tree/main/public/images/blog/2024/01/19/optimized


another area is a picture gallery:
- https://github.com/terijaki/vcmuellheim/blob/main/app/fotos/page.tsx
- https://vcmuellheim.de/fotos

**Comment by terijaki** [comment]
Damn! I am using https://github.com/actions/configure-pages/ during my build and deploy process.
I didn't notice before that it disables image optimisation. Completely messes things up.
<img width="740" alt="image" src="https://github.com/Niels-IO/next-image-export-optimizer/assets/590522/634f9cc7-e8d4-4931-8fee-7f1245c48cfd">

**Comment by Niels-IO** [comment]
Hi @terijaki,

Is it now working as expected?

I noticed two things in your use of the library:
1. When you specify a width and height, you are telling [Next.js that this is the size you want it to be displayed](https://nextjs.org/docs/pages/api-reference/components/image#width). So naturally, it omits the other sizes in the srcset and only uses the requested size in the image element (or the nearest larger size in the sizes array). If you want to have a dynamic behavior, you can specify fill, and then it will generate the complete srcset.

If you take this example of your website: https://github.com/terijaki/vcmuellheim/blob/1728c28829fad49e30b97f25567f438b8445e20e/app/components/homepage/HomeIntro.tsx#L21-L28
and remove the unoptimized prop, you get the expected behavior.

2. You are using unoptimized in several places, any reasons for that?

**Comment by terijaki** [comment]
@Niels-IO it is working as expected in most places yes. 🤗

I have totally forgotten about the unoptimised parameter.... I've added it to the images on the homepage above the fold because I didn't like the blur effect. That being said the issue was also that the optimised webp images were not being used, so the blur effect was display too long, until the large jpgs were loaded.

Not that things are working, I'll go over every place to review what I've done this past month in terms of specific sizes and unoptimised flags 😅

In some places it is intended for sure (sponsor/brand logos). Other area's are ok-ish but not perfect yet.

Thanks for your help, creating and maintaining this tool!

**Comment by Niels-IO** [comment]
@terijaki Thanks a lot! Nice to hear that it is useful!

Let me know if you come across a situation again where it is not working as you would expect.

**Comment by el-j** [comment]
@terijaki i tried to get this work but sadly without luck. if i put the `fill` prop the srcset is created. but i cannot use fill as it destroys my layout. here is the running export build as pre-release. 

maybe u have any idea why this is?
https://el-j.github.io/fabianalthaus.de

**Comment by terijaki** [comment]
@el-j the **fill** property can be tricky to work with but once you got the hang of it, this is the way to go.
btw this has nothing to do with Niels-IO work as it using the NextJs image component.

See: https://nextjs.org/docs/pages/api-reference/components/image#fill
> The parent element must assign position: "relative", position: "fixed", or position: "absolute" style.

In some situations it might be a valid solution to put a wrapper around your images and set their position to relative.

**Comment by el-j** [comment]
@terijaki indeed i tried with a wrapper to trick the `fill` prop but this does not work for me. 
so i am in need for the srcSet get created correctly. but it does not as u see from the exported-code. i am wondering where i can find the example @Niels-IO is talking about, as i would like to check against my code.

**Comment by Niels-IO** [comment]
Hi @el-j,

here is a good section of the Next.js docs to understand responsive images:
https://nextjs.org/docs/pages/api-reference/components/image#responsive-images

I hope that helps for your use case

**Comment by el-j** [comment]
hi @Niels-IO no it does not. if it would help i wouldn't have created this issue. i have test and tried all these, without getting a good srcSet. so in fact with fill, and wrapper it just breaks the whole layout so its not a solution. 

so any idea how i get the srcSet from your package written to the output dom? i mean... all the versions of images are created and sitting there... just the image-srcset does not know them so cannot use them.

**Comment by Niels-IO** [comment]
@el-j  
I think there is very likely a CSS solution that allows you to use any solution in the previous link and won't break your layout.

**Comment by el-j** [comment]
hi again, so i created a codesandbox that shows the issue. for me it just seems the srcSet is just ignored ...

[sandbox](https://codesandbox.io/p/devbox/next-image-export-optimizer-srcset-9wq479?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls08afdy00073b6hf9iym8px%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls08afdy00023b6hme5ino0y%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls08afdy00043b6h80hyeo11%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls08afdy00063b6h6jhb1h3h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50.83498456%252C49.16501544%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls08afdy00023b6hme5ino0y%2522%253A%257B%2522id%2522%253A%2522cls08afdy00023b6hme5ino0y%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cls08afdy00063b6h6jhb1h3h%2522%253A%257B%2522id%2522%253A%2522cls08afdy00063b6h6jhb1h3h%2522%252C%2522activeTabId%2522%253A%2522cls0a8zuz03o63b6hiboixb2v%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cls0a8zuz03o63b6hiboixb2v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cls08afdy00043b6h80hyeo11%2522%253A%257B%2522id%2522%253A%2522cls08afdy00043b6h80hyeo11%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls09ckkg01l13b6hw90c75h1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cls09ckp900teefge0jxq6cdk%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cls09ckkg01l13b6hw90c75h1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A25.049139293363126%257D)


myproject-issue:
<img width="1040" alt="image" src="https://github.com/Niels-IO/next-image-export-optimizer/assets/2795534/95e1f1ae-4798-4072-bd39-62731b28efdb">

from codesandbox issue is the same:
<img width="1068" alt="image" src="https://github.com/Niels-IO/next-image-export-optimizer/assets/2795534/9f1ac5db-806c-4a5c-9943-76d640346bf5">

**Comment by el-j** [comment]
and as i see from my own screenshots now, in my project for every source size it's always the 1080p file in the attributes,
in the codesandbox the list is correct, but not correctly used...

**Comment by Niels-IO** [comment]
Hi @el-j,

thanks for the codesandbox. It works as expected:
<img width="685" alt="image" src="https://github.com/Niels-IO/next-image-export-optimizer/assets/47059882/129a50d9-939f-4fcb-a9ee-d6c504f4ea9f">
When you load a page with that small width, the correct src is the smallest source in the [deviceSizes](https://nextjs.org/docs/pages/api-reference/components/image#devicesizes) array. Which is 640px.

The behavior of most browsers is that once you load a larger image file (in the case you had the browser larger at one point and then made it smaller) that it just uses the larger image.

**Comment by el-j** [comment]
that is so strange...when i reload the codesandbox it really works. but if i do it with my project i just have always the biggest version loaded after the `opt-10` version. does not matter which view-port size i have... 

when i investigate deeper the srcSet always have the same sizes for all variantes.
build on github:
<img width="1031" alt="image" src="https://github.com/Niels-IO/next-image-export-optimizer/assets/2795534/47988ad2-1f24-4902-9132-d159693fd85e">

local dev:
<img width="1034" alt="image" src="https://github.com/Niels-IO/next-image-export-optimizer/assets/2795534/be97f1d3-f7c2-4ab1-9e71-88cb8a42a278">


@Niels-IO u have any idea why the list of srcSet always contains the biggest version for every size?

**Comment by el-j** [comment]
@Niels-IO here is the screenshot. it's not so clean as i sadly have to transfrom the incoming string to match the correct image from the `staticImagesObject` . 
<img width="583" alt="image" src="https://github.com/Niels-IO/next-image-export-optimizer/assets/2795534/b623c3b6-635d-4038-ae54-2a815601a87e">

the image-object is ontop of this code like:
```ts
import "foo" from "../imagepath/foo.jpg"
import "bar" from "../imagepath/bar.jpg"
const staticImagesObject = { foo, bar } as { [key: string]: ExportedImageProps["src"] };
```

<img width="387" alt="image" src="https://github.com/Niels-IO/next-image-export-optimizer/assets/2795534/e20fbddc-4392-4cda-bffd-d855d35c4b31">

**Comment by Niels-IO** [comment]
@el-j What would happen if you remove the wrapping div? I think the bug might be related to CSS styling

**Comment by el-j** [comment]
@Niels-IO then i am back where i was before with the same result: all srcset variants contain the biggest version.

**Comment by Niels-IO** [comment]
@el-j 
I would recommend to start with a fresh page, add one image and see if this works. Then continuously add the complexity that you currently have in your code and see where it breaks.

**Comment by el-j** [comment]
@Niels-IO 
so now i made a dev-page. ueing my  `Images` component and the  `ExporteImage` component:
<img width="663" alt="Screenshot 2024-01-30 at 17 45 19" src="https://github.com/Niels-IO/next-image-export-optimizer/assets/2795534/c58b0597-407e-4a0e-9329-dd5dec564ee2">

which results in the same behaviour: 
<img width="1023" alt="image" src="https://github.com/Niels-IO/next-image-export-optimizer/assets/2795534/68f288c4-a8bc-46e3-b0ad-e08cf5f162f2">

any idea? i dont understand why this is not working in my case.

**Comment by Niels-IO** [comment]
That should work as you have it. Can you send a screenshot from the next.config.js please?

**Comment by el-j** [comment]
this is my config:
<img width="577" alt="Screenshot 2024-01-31 at 00 06 21" src="https://github.com/Niels-IO/next-image-export-optimizer/assets/2795534/050abceb-e829-40da-905e-7b261114b3c1">

and meanwhile i was so keen to investigate what u are doing and stumbled about these comment lines:
https://github.com/Niels-IO/next-image-export-optimizer/blob/c20cf5cabd33f581408a62a44c65bf9882fc6734/src/optimizeImages.ts#L225

could this be a reason? sorry i am guessing wild ... 
ooh... i have little idea what could be a reason ... *tinkering*

**Comment by el-j** [comment]
ok sooooo: i moved my images all into the project, out of the public folder. and TADA it works.

the second line in the code example doing `import me from '../photos/me.jpg'` 
nextjs wants them to be in the src-folder if u want them static... *hmpf*
they should add this line to the docs...
https://nextjs.org/docs/app/api-reference/components/image#responsive-image-using-a-static-import

i really appreciate your help! thank u very much! u have done a very helpful package here!
