### ISSUE TITLE
Output folder not being created on build.

### ISSUE THREAD

**Issue by joebentaylor1995** [Niels-IO/next-image-export-optimizer#199]
After battling with 10 errors for 3 images in the console log for a couple of hours I realised, that when running  `next build && next-image-export-optimizer` and then serving this, the assets folder for the optimised images never gets made or generated.

I have the exact same config as the docs, but i looked in the `out` folder and there are no optimised images folder anywhere.

Using Next 14.1.0
![Screenshot 2024-01-29 at 17 38 40](https://github.com/Niels-IO/next-image-export-optimizer/assets/54585427/255f56e1-dc93-4fe9-9848-7aca21afcc03)

**Comment by joebentaylor1995** [comment]
![Screenshot 2024-01-29 at 17 40 00](https://github.com/Niels-IO/next-image-export-optimizer/assets/54585427/2f647edd-ef2d-4d2b-be6b-aadccd9f687f)
![Screenshot 2024-01-29 at 17 40 06](https://github.com/Niels-IO/next-image-export-optimizer/assets/54585427/7029b391-a32b-4b5d-8150-2ffde0a13c49)

**Comment by joebentaylor1995** [comment]
![Screenshot 2024-01-29 at 17 40 06](https://github.com/Niels-IO/next-image-export-optimizer/assets/54585427/70aa589c-5851-464d-a026-98390119b175)
![Screenshot 2024-01-29 at 17 40 58](https://github.com/Niels-IO/next-image-export-optimizer/assets/54585427/1bf2175d-902c-4621-8083-25e99547a07e)

**Comment by joebentaylor1995** [comment]
![Screenshot 2024-01-29 at 17 40 06](https://github.com/Niels-IO/next-image-export-optimizer/assets/54585427/addda828-0ed7-4c23-a520-5e7f1777370d)
![Screenshot 2024-01-29 at 17 42 46](https://github.com/Niels-IO/next-image-export-optimizer/assets/54585427/baac8799-b281-4dbb-b941-c1bfd154ee65)

**Comment by Niels-IO** [comment]
Hi @joebentaylor1995,

Just to be sure: did you change the build script in package.json?

**Comment by joebentaylor1995** [comment]
Yes i did (it doesnt have the `next export` as next config is suggested to have the export enabled under `output: 'export'`)
![Screenshot 2024-01-29 at 18 34 12](https://github.com/Niels-IO/next-image-export-optimizer/assets/54585427/46a7e78e-5a39-492d-b7e8-2a44ed56ccbf)

**Comment by joebentaylor1995** [comment]
So, i usually run: `npm run build && npm run serve` to view locally the entire build

**Comment by Niels-IO** [comment]
@joebentaylor1995 Do you only have remote images? Have you created a remoteOptimizedImages.js as detailed in the README?

I just tested the library with the newest Next.js version and the optimized images are generated as expected.

What is the terminal output for the build script?

**Comment by joebentaylor1995** [comment]
No, my images are all local.

My terminal output:
![Screenshot 2024-01-30 at 12 43 50](https://github.com/Niels-IO/next-image-export-optimizer/assets/54585427/8055b562-6914-4917-9a50-6e0e203ed445)

**Comment by Niels-IO** [comment]
It seems that you have no pictures in the "public/images" folder, and not used static import for images. In your posted example above you are using a remote image.

How are you using the ExportedImage component?

**Comment by joebentaylor1995** [comment]
Og theres plenty of images in the public folder...

The dummyData images are what im trying to use

![Screenshot 2024-01-30 at 12 49 10](https://github.com/Niels-IO/next-image-export-optimizer/assets/54585427/a4bbe004-32cc-4365-b007-b08e98bff89c)

**Comment by joebentaylor1995** [comment]
DummyData as a const in page.jsx

passed via props
![Screenshot 2024-01-30 at 12 49 53](https://github.com/Niels-IO/next-image-export-optimizer/assets/54585427/6875462f-72e3-45b9-a732-f6ecd7f66077)


into this:
![Screenshot 2024-01-30 at 12 49 45](https://github.com/Niels-IO/next-image-export-optimizer/assets/54585427/14c64385-034e-468c-a632-ae50f9201f37)

**Comment by Niels-IO** [comment]
In your next.config.js you specified "public/images" as the image folder where this library looks for images. Change that to "public/dummydata" or move all your images to the "public/images" folder...

**Comment by joebentaylor1995** [comment]
Okay,. will give that a go now, I may have overlooked the folder

**Comment by joebentaylor1995** [comment]
I think we can close this now, thanks for the help @Niels-IO
