### ISSUE TITLE
Issue with query string get params

### ISSUE THREAD

**Issue by ruslkovalen123** [Niels-IO/next-image-export-optimizer#203]
When query string params are explicity present in "src" attribute of ExportedImage remote images are not optimized
taking example from your example folder adding get params.
either specifiyng query string get params in remoteOptimizedImages or nor
<img width="699" alt="Screenshot_1" src="https://github.com/Niels-IO/next-image-export-optimizer/assets/118004593/dea27ee7-e8a9-41f9-bc19-c9ae4dd0613f">
<img width="839" alt="Screenshot_2" src="https://github.com/Niels-IO/next-image-export-optimizer/assets/118004593/3b2895d0-7ac1-4982-bb4a-6c2097f539a3">
<img width="853" alt="Screenshot_3" src="https://github.com/Niels-IO/next-image-export-optimizer/assets/118004593/b0354a6d-17a8-4c5a-ac55-6fb302793935">

**Comment by Niels-IO** [comment]
Hi @ruslkovalen123,

Thanks for the bug report. I will take a look. Hopefully in May.

**Comment by Niels-IO** [comment]
Hi @ruslkovalen123,

This should be fixed in v1.14.0 now. Can you please confirm?
