### ISSUE TITLE
Invalid next.config.js

### ISSUE THREAD

**Issue by psirenny** [Niels-IO/next-image-export-optimizer#23]
Next.js throws a warning about the library's custom **next.config.js** options:

https://nextjs.org/docs/messages/invalid-next-config
<img width="733" alt="Screen Shot 2022-07-27 at 5 40 30 AM" src="https://user-images.githubusercontent.com/463178/181216552-d1842ecb-64ee-4e0f-b2f5-13f0eac0e9e7.png">

I'm not sure what the alternative is. Perhaps next-image-export-optimizer options could be stored elsewhere?

**Comment by Niels-IO** [comment]
Hi @psirenny,

Thanks for the issue. I was ignoring this warning so far. I will think about the best place to put the configuration and keep backward compatibility as well.

**Comment by Niels-IO** [comment]
Hi @psirenny, 
I decided to put all the config variables in the environment object. You can check it out in v0.12.1 and refer to the readme for the new naming of the config variables. 
It should be backward compatible for everyone that uses the "old" config.

Done it PR #26

**Comment by psirenny** [comment]
Thanks!
