### ISSUE TITLE
ESM -> Failing to load remoteImages

### ISSUE THREAD

**Issue by PhilGale92** [Niels-IO/next-image-export-optimizer#230]
Hey,

Quick note (appriciate the libray, was exactly what i needed!).

Having problems where i have a project based on ESM; and having a `remoteOptimizedImages.js` file is failing due to being required in via the library.

Would it be possible to make it a customisable option (maybe via package.json argument) to be able to set the filename / extension.

As in a quick fork I made just to unblock myself, if i set it to `remoteOptimizedImages.cjs` everything goes through fine.
Thought id get thoughts before i make a proper PR to move it upstream via config when i get a momento 

Thanks!

**Comment by monemagrafica** [comment]
same here!
