### ISSUE TITLE
No warning / error message on `nextImageExportOptimizer_imageFolderPath` doesn't include word `public`

### ISSUE THREAD

**Issue by xlebenny** [Niels-IO/next-image-export-optimizer#234]
### Config

- `next.config.mjs`

```javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "export",
  images: {
    loader: "custom",
  },
  transpilePackages: ["next-image-export-optimizer"],
  env: {
    nextImageExportOptimizer_imageFolderPath: "<someFolderWithoutPublicString>",
  },
};

export default nextConfig;
```

### tsx

- none

### Output
```
---- next-image-export-optimizer: Begin with optimization... ---- 
Found 0 supported images in .temp, static folder and subdirectories and 0 remote image.

Copy optimized images to build folder...

Finished optimization in: NaN days
---- next-image-export-optimizer: Done ---- 
```

The `next-image-export-optimizer-hashes.json` file is generated after running `next-image-export-optimizer`, but no images are actually processed.

It looks like the issue might be related to [here](https://github.com/Niels-IO/next-image-export-optimizer/blob/master/src/optimizeImages.ts#L266C9-L266C49), which seems to exclude folders/files without `public` in their name.

_

PS: I think this is a good approach for let user know it's for "public" without using the default public folder, my case is put images to R2 rather than put into Cloudflare Pages (25MB limit)

**Comment by Niels-IO** [comment]
Hi @xlebenny 

I added the warning message. Thanks for your report!
