### ISSUE TITLE
basePath

### ISSUE THREAD

**Issue by brianblip** [Niels-IO/next-image-export-optimizer#238]
hello @Niels-IO, I just want to ask if there's any workaround on the basePath wherein I won't need to add it manually on my images, because I have a lot of images per page

**Comment by Niels-IO** [comment]
Hi @brianblip,

You could access process.env.__NEXT_ROUTER_BASEPATH so that your components automatically update.
```javascript
import ExportedImage from "next-image-export-optimizer";
import testPictureStatic from "PATH_TO_IMAGE/test_static.jpg";
const basePath = process.env.__NEXT_ROUTER_BASEPATH
<ExportedImage
  src={testPictureStatic}
  alt="Static Image"
  basePath={basePath}
/>;
```

**Comment by brianblip** [comment]
I tried that but its not working on my side. It cannot read my basePath

**Comment by Niels-IO** [comment]
Okay. Unfortunately, the way it is currently implemented is also the documented way in the Next.js docs:
https://nextjs.org/docs/app/api-reference/next-config-js/basePath#images

**Comment by brianblip** [comment]
Yeah that's what I did,  I manually add it

**Comment by Niels-IO** [comment]
I will close this as I am hesitant to add an undocumented way to retrieve the basePath to this package
