### ISSUE TITLE
"next-image-export-optimizer" doesn't exit automatically when using Bun

### ISSUE THREAD

**Issue by arvilmena** [Niels-IO/next-image-export-optimizer#240]
First of all, great work @Niels-IO 
I am not sure why NextJS doesn't do this by default for static export.
Isn't the point of building your whole site locally to be able to optimise all the assets including images?

As for my bug report. I am using [bun](https://bun.sh/) on my NextJS project.
This library works well until at the very last part when it doesn't exit automatically after running the post-build script: "next-image-export-optimizer"

<img width="827" alt="image" src="https://github.com/user-attachments/assets/c1c50bd3-5269-4e72-a51a-9131c3f5c34f">

I wish to include the static export on my CI build process, but since this is not exiting automatically, the CI simply times out even though it has successfully export the assets.

I have created repro using this fork, under the `feat/bun` branch:

https://github.com/arvilmena/fork--next-image-export-optimizer/tree/feat/bun

I hope you can take a look on this.

Thanks!

**Comment by Niels-IO** [comment]
I added the termination code (your PR did not go through CI)
