### ISSUE TITLE
Hi, I use the component ExportImage but it come to an error says "filePath.split is not a function", how do i fix it?

### ISSUE THREAD

**Issue by Niels-IO** [Niels-IO/next-image-export-optimizer#27]
Hi, I use the component ExportImage but it come to an error says "filePath.split is not a function", how do i fix it?

_Originally posted by @milkeddy1 in https://github.com/Niels-IO/next-image-export-optimizer/issues/24#issuecomment-1200419408_

**Comment by Niels-IO** [comment]
Hi @milkeddy1 ,
The error means that you probably imported an image like this:
```
import logo from '../public/images/logo.png'
<ExportedImage src={logo} />
```

Unfortunately, this is not supported. Please specify the src like this:
```
<ExportedImage src='images/logo.jpg' />
```

**Comment by milkeddy1** [comment]
You're right! Thanks.

**Comment by phiresky** [comment]
Would it be possible to support this?

Doing it this way sets the width property without having to specifiy it manually, with a string path src it wants to have an explicit width set: `Error: Image with src ... must use "width" and "height" properties or "layout='fill'" property.`

https://nextjs.org/docs/basic-features/image-optimization#local-images

**Comment by Niels-IO** [comment]
Hi @phiresky,

I looked into it, and I think it is impossible, as far as I know.

When you import an image like this:
`
import image from "../public/images/chris-zhang-Jq8-3Bmh1pQ-unsplash.jpg";
   <ExportedImage
            src={image}
            layout="fill"
            id="test_image"
            objectFit="cover"
            priority={true}
            alt={"test_image"}
    />
`


the src property becomes

`
{
blurDataURL: "/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fchris-zhang-Jq8-3Bmh1pQ-unsplash.921260e0.jpg&w=8&q=70"
height: 4000
src: "/_next/static/media/chris-zhang-Jq8-3Bmh1pQ-unsplash.921260e0.jpg"
width: 6000
}
`

It obfuscates the correct image location in the public folder, so I cannot work with the image in the ExportedImage component.

**Comment by phiresky** [comment]
thank you for the response. i think it's possible with restrictions. My workaround currently looks as follows:

1. I wrap ExportedImage to set width and height and src as ExportedImage expects them (this could be done within the library)

```ts
export default function ExportedImageCompatible(_props: ImageProps) {
  const { src: _src, ...props } = _props;
  let src = _src;
  console.log(src);
  if (typeof src !== "string") {
    if ("default" in src) {
      src = src.default;
    }
    if (!props.width) props.width = src.width;
    if (!props.height) props.height = src.height;
    src = src.src;
  }
  return <ExportedImage {...props} src={src} />;
}
```

2. I set the following configuration:

```
    nextImageExportOptimizer_imageFolderPath: "out/_next/static/media",
    nextImageExportOptimizer_exportFolderPath: "out",
```

next.js copies the images to the `out/_next/static/media` directory during the build step. Then next-image-export-optimizer loads those images and transformes them from there

This seems to work ok so far

**Comment by jdolinski1** [comment]
If the static import of image - and thus omitting the width/height props - is not supported, then it should be removed from the example mentioned in [README.md](https://github.com/Niels-IO/next-image-export-optimizer#readme)

```
// Or with static import
import ExportedImage from "next-image-export-optimizer";
import testPictureStatic from "PATH_TO_IMAGE/test_static.jpg";

<ExportedImage
  src={testPictureStatic}
  alt="Static Image"
  layout="responsive"
/>;
```

**Comment by Niels-IO** [comment]
Hey @jdolinski1, this is actually a very recent functionality that I implemented. So the library works now with statically imported images as well 🙂

**Comment by jdolinski1** [comment]
Ah, sorry! Thanks.
