### ISSUE TITLE
Images components are not exported after a next build

### ISSUE THREAD

**Issue by johann-taberlet** [Niels-IO/next-image-export-optimizer#28]
Hey there,
just discovered your (seems like :p) awesome package.

I had a try on it but when I export my site by running `next build && next export && next-image-export-optimizer`, I can see that all my images are well optimised in different sizes and copied into the out folder but when I inspect the resulting html, no img tag at all are injected.  Images appears well on `next dev`.

I'm definitely doing something wrong but I don't find what. I followed the instructions here with the exact same config. My images are in the public folder and I wrote a basic component like this:

` <ExportedImage src="images/destination/image-europa.png" layout="fill" />`

Any ideas on what I'm doing wrong ?

Edit: I uploaded this training project here https://github.com/johann-taberlet/space-tourism-website

**Comment by Niels-IO** [comment]
Hi @johann-taberlet,

Thanks a lot! I am not 100% sure I understand the problem. The ExportedImage component wraps around the Next.js Image component, which produces an img tag in the final HTML. 

I just run your project and can see the img tag in the developer tools:
<img width="2559" alt="image" src="https://user-images.githubusercontent.com/47059882/182822062-62a51655-de4a-4685-922f-82ac8de3fb08.png">

What is it exactly that you are missing?

**Comment by johann-taberlet** [comment]
Mmh... Did you exported it and launched it via out/index.html ? If I do that by right clicking on index.html "Open with Five Server" I don't have any images but I also realised that I don't have any styles on my texts as well..
![SCR-20220804-hbl](https://user-images.githubusercontent.com/9981334/182825782-dc9d6b75-43cb-459a-8f33-c22b1d41f63e.png)
.

So there's definitely something wrong on what I'm doing (learning Next as well...)

**Comment by Niels-IO** [comment]
Hi @johann-taberlet,
the exported version did work for me as well. 
What I did:
npm run build
cd /out
npx http-server

This will spin up a server that serves the files in the out file. I can see the optimized images in their respective folders.

**Comment by johann-taberlet** [comment]
Oh god... The problem was about live server (VSCode extension) that actually can't serve exported next website... (no clues on why)
With `npx http-server` everything works perfectly!
Really sorry for this fake issue and would like to thank you a lot for your help and your work on this package.

You can delete this if you want.

Thanks!

**Comment by Niels-IO** [comment]
No worries! Hope everything works from now on :)
