### ISSUE TITLE
Pipeline fail at next-image-export-optimizer script

### ISSUE THREAD

**Issue by agniAZ** [Niels-IO/next-image-export-optimizer#29]
Configuration used:

"next": "^12.2.3",
"react": "^18.2.0",
"next-image-export-optimizer": "^0.12.1",

I'm currently trying to run the image export opti in my pipeline (is pretty generic, nothing special going on in there) but for some reason it fails after yarn export at **next-image-export-optimizer/src/optimizeImages.js:89**

Which is  **const legacyPath = nextjsConfig.images?.nextImageExportOptimizer;**

With an error **SyntaxError: Unexpected token '.'** after the question mark.

Could you please help me out, and point me at what I'm doing wrong here :)

(locally it runs fine, of course haha)

TIA

**Comment by Niels-IO** [comment]
Hey @agniAZ,
Hard to say, especially since it is working locally. Can you ensure that the config file is present in your CI pipeline?

**Comment by dzbrozek** [comment]
which node version do you use? The optional chaining was added around node 14

**Comment by andreasalfven95** [comment]
I had a huge problem figuring out why this problem. After reading @dzbrozek comment about updating node, it works like a charm! A million thanks for the answer and the great package!

**Comment by Niels-IO** [comment]
Yeah, I am using node 16. Maybe I should re-write it so that it supports node version 14. Sorry for the inconvenience!

**Comment by agniAZ** [comment]
@Niels-IO @dzbrozek yeah it seems like the node version in the pipeline fixed the problem, at first I though the change was coming from the switch from **yarn** to **NPM**, but the actual change that fixed the pipeline was the Node update to 16.x

but yeah, it might be a good idea to support Node 14.x or document it somewhere as a 'good to know'

**Comment by dzbrozek** [comment]
@Niels-IO add engines to package.json, that will be helpful

**Comment by Niels-IO** [comment]
HI @dzbrozek,
Good idea. I added node 16 as a requirement. Supporting node 14 seems more difficult; I couldn't get it to work.
