### ISSUE TITLE
Image path not resolved if used with the basePath property

### ISSUE THREAD

**Issue by lansolo99** [Niels-IO/next-image-export-optimizer#3]
Hi and congrats for taking the initiative of this package!

I'm often facing use-case where I have to deploy static pages under a subfolder in a shared hosting.
Unfortunately it doesn't work with the needed next.conf.js `basePath` property, to resolve asset. The built path doesn't take that into account.

I would like to help but I'm not sure being skilled enough for this 🤭.

Tell me if you have recommandation regarding this bug or needed contribution, I'm really interested to get this package working.

**Comment by Niels-IO** [comment]
Hi @lansolo99, glad you like the package!

Regarding your problem: 

Let's say you are using the standard out directory. Currently, all images in public/images will be copied to out/images. If your basePath is "example", would it be sufficient if the optimized images get copied to out/**example**/images?

(You could try it by manually creating this directory after the Next.js export command and the next-image-export-optimizer command.)

**Comment by lansolo99** [comment]
@Niels-IO Ok my fault, after digging a bit, I realized it was because I omitted to use the prop `trailingSlash` to `true` within next.config.js. It works like a charm then, you can consider it resolved 🙂.

By the way, I also noted 2 things:
- There is no TS file declaration for the package, as I think most of people work with it nowadays.
- The `storePicturesInWEBP`set to false still produce webp files (for a jpg file), not a big deal but weird

**Comment by Niels-IO** [comment]
Hi @lansolo99,

Thanks for all the feedback! Glad it is now working for you. :)

The storePicturesInWEBP flag actually had a bug, and it is resolved now. Thanks for noting it!
Regarding TS: to rewrite it from JS to TS would be the next step for this package. To be honest, I have to get more into TS first. :)

**Comment by brianblip** [comment]
Hi, this package is great and it helps me with my images, my problem is my basePath wherein if I try to go to the url of my basePath it gives me a 404 error. also I have a lot of images on multiple components per page so is there a way to set the basePath dynamically? 

@Niels-IO
