### ISSUE TITLE
Does this work without specifying width/height?

### ISSUE THREAD

**Issue by augustblack** [Niels-IO/next-image-export-optimizer#34]
one of the advantages of using next/image is that it can suss out width/height.

It seems like this library doesn't work unless you specify width/hight or have a containing div where the width and height are specified.

eg, the following works fine with next/image but will just show up empty (zero width and height):

```
          <div className='md:float-right md:relative w-full md:w-1/3 md:ml-4 md:mb-2'>                                                         
            <ExportedImage                                                                
              className="rounded"                                                                                     
              placeholder='blur'                                                          
              src={profile.src}                        
              alt={profile.alt}                                                                        
              sizes="(max-width: 768px) 100vw,                                            
              (max-width: 1200px) 50vw,         
              33vw"                      
            />       
          </div>    

```

**Comment by Niels-IO** [comment]
Hi,
Next.js can figure out the width and size of the image if you import it using the syntax described here:
https://nextjs.org/docs/basic-features/image-optimization#local-images

In your example, you are correct that you have to specify the height additionally in the outer wrapper. Otherwise, there is no way to know what height your image should be rendered. Furthermore, you would have to set the layout property to fill.


```diff
- <div className='md:float-right md:relative w-full md:w-1/3 md:ml-4 md:mb-2'>         
+ <div className='md:float-right h-52 md:relative w-full md:w-1/3 md:ml-4 md:mb-2'>                                                  
          <ExportedImage                                                                
            className="rounded"                                                                                     
            placeholder='blur'                                                          
            src={profile.src}                        
            alt={profile.alt}
+           layout={"fill"}                                                                        
            sizes="(max-width: 768px) 100vw,                                            
            (max-width: 1200px) 50vw,         
            33vw"                      
          />       
</div>   
```

**Comment by augustblack** [comment]
Thanks for the reply. And, thanks for this awesome library.

> Next.js can figure out the width and size of the image if you import it using the syntax described here:
> https://nextjs.org/docs/basic-features/image-optimization#local-images

Yes, that is why it works with next/image afaict.  Next can suss out the width/height of the image and use it as if it were a normal <img> that just places the image relative to its size and shape (portrait/landscape)

The problem I see with any `layout="fill"` situation where you might fill with various images is that you need to either accept a predefined width/height  portrait/landscape/square or manually define width and height for each image and calculate sizes relative to veiwport.   

I notice that you only accept the string type for `src` and not the `string | StaticImageData`. Is there a reason for that?  

Looking briefly at the code, it seems like one could also accept `StaticImageData` and then have a drop-in replacement for next/image (converting to string in cases where needed)

I could investigate if you thought that would be useful

**Comment by Niels-IO** [comment]
Hi @augustblack,
Thanks for the push. I found a way to support static images and published a new version, 0.14.0

Could you please try it if it works as you would expect?

**Comment by augustblack** [comment]
hey @Niels-IO 

looking good!  It seems to be working.

I only notice that maybe the `placeholder='blur'` is not being calculated.  Could that be the case?

**Comment by augustblack** [comment]
ooh, I also just noticed a few other things.

It seems like the images loaded via imported path are not getting resized, but are using the full-size image.

I am also seeing a lot of 404s in the console as it tries to load images with paths such as:

`http://localhost:8000/<namedpath>/_next/static/media/nextImageExportOptimizer/media01.eb95ed1a-opt-10.WEBP`

I assume that should be something like : `http://localhost:8000/_next/static/media/...`

**Comment by Niels-IO** [comment]
That is strange. The placeholder generation, as well as the resizing, are working in the example Next.js in this library. One thing to note is that you have to test it with the exported, static app. (export it and then serve the static files with any server like npx http-server)
In the development mode, it falls back to the original src.

Are the image paths actually containing "namedpath" or is it a placeholder for diverse paths of your images? Could you please provide an example of one implementation of the ExportedImage component?

**Comment by augustblack** [comment]
thanks for the reply and your patience.

yes, I am exporting to out and running a simple web server to deliver the html locally on 8000

I _think_ I see what is happening.

I have a next.js layout such as:
```
pages/index.tsx
pages/[slug].tsx
```

when the `pages/[slug].tsx` gets rendered/exported as:

```
out/index.html
out/<slug>/index.html
```

in my case, all the images in `out/index.html` are okay (using the optimized versions), but the ones in `out/<slug>/index.html are only using the full unmodified versions.

Could it be that the replaced url that next-image-export-optimizer spits out seems to assume all pages are at the top level and that the url is relative?  Maybe a quick fix would be to set the replaced url as absolute starting with `/_next/...` ??

Thanks for checking all of this out and, again, for the work going into this library.

**Comment by Niels-IO** [comment]
Hi @augustblack,

Thank you very much for the support. You were exactly right; the problem existed only with nested paths. In the end, it was a simple fix:

If the generated image URL starts with a slash, it resolves to the correct complete URL with the host added in front. 
The nested path is appended to the host if the starting slash is missing.

I published a new version that should fix the problem. (v0.14.1)

**Comment by augustblack** [comment]
Hi @Niels-IO 

this seems to be working great now!  Very cool to see this in action.

I have one small thing to mention and perhaps it should be a new issue.

I notice that using the plain next/image, next will load the page with the image in place and proper sizing.  This keeps the page from reflowing.

However, with next-image-export-optimizer, the page loads the text first, then puts in the blurred placeholder image.  This makes the page load once, then reflow again after it inserts the image.   I wonder if something could be done to improve that.

**Comment by Niels-IO** [comment]
Hi @augustblack,

I think I solved the layout shift problem for the static images. Could you please test the new version in your setup?

**Comment by augustblack** [comment]
working great now!
