### ISSUE TITLE
Segmentation fault (macos M1, sharp v0.31.0)

### ISSUE THREAD

**Issue by crucialfelix** [Niels-IO/next-image-export-optimizer#37]
Hi,

I am getting segfaults from next-image-export-optimizer.

```
---- next-image-export-optimizer: Begin with optimization... ----
Found 44 supported images in public/images, static folder and subdirectories.
Using sizes: 10,16,32,48,64,96,128,256,384,640,750,828,1080,1200,1920,2048,3840
Start optimization of 44 images with 17 sizes resulting in 748 optimized images...
██ 5% | ETA: 117s | 42/748 | Total size: 6.5 MBsh: line 1: 25707 Segmentation fault: 11  next-image-export-optimizer
```

I am on macos M1. There is an issue on sharp: https://github.com/lovell/sharp/issues/3048
but that looks like it was resolved with the latest release [v0.31.0](https://www.npmjs.com/package/sharp/v/0.31.0) which is what your package uses, and what did get installed.

Sometimes it even segfaults during next build:

```
info  - Creating an optimized production build .sh: line 1: 27459 Segmentation fault: 11  next build
```

It only gets through 8 resizings before it happens

```
.rw-r--r--    82 crucialfelix 22 Sep 09:24 aaron-burden-1381021-unsplash-opt-10.WEBP
.rw-r--r--   120 crucialfelix 22 Sep 09:24 aaron-burden-1381021-unsplash-opt-16.WEBP
.rw-r--r--   322 crucialfelix 22 Sep 09:24 aaron-burden-1381021-unsplash-opt-32.WEBP
.rw-r--r--   600 crucialfelix 22 Sep 09:24 aaron-burden-1381021-unsplash-opt-48.WEBP
.rw-r--r-- 1,012 crucialfelix 22 Sep 09:24 aaron-burden-1381021-unsplash-opt-64.WEBP
.rw-r--r-- 2.1Ki crucialfelix 22 Sep 09:24 aaron-burden-1381021-unsplash-opt-96.WEBP
.rw-r--r-- 3.5Ki crucialfelix 22 Sep 09:24 aaron-burden-1381021-unsplash-opt-128.WEBP
.rw-r--r--  13Ki crucialfelix 22 Sep 09:24 aaron-burden-1381021-unsplash-opt-256.WEBP
.rw-r--r--     0 crucialfelix 22 Sep 09:24 aaron-burden-1381021-unsplash-opt-384.WEBP
```
(last one is size 0)

I have just local images, config is simple:

```js
{
 // ...
  images: {
    loader: "custom",
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
  },
  env: {
    nextImageExportOptimizer_imageFolderPath: "public/images",
    nextImageExportOptimizer_exportFolderPath: "out",
    nextImageExportOptimizer_quality: 75,
    nextImageExportOptimizer_storePicturesInWEBP: true,
    nextImageExportOptimizer_generateAndUseBlurImages: true,
  },
}
```

Thank you!

**Comment by Niels-IO** [comment]
Hi @crucialfelix,

Thanks for the bug report! 🙂 Is it that you still receive this segmentation fault error even though the bug should be fixed by sharp v.31.0?

I am not sure what is in my power to fix the issue.

**Comment by crucialfelix** [comment]
Yes, I am still getting segmentation faults despite their update.

I'm not sure you can do anything either, but I wanted to report it to you.  Perhaps it will help somebody else searching.

**Comment by Niels-IO** [comment]
Hi @crucialfelix,

Yes, good to know that there is an issue. I also use an M1 processor but haven't encountered this bug yet. I hope it will get resolved in a future sharp version. I will close this issue for now.

**Comment by crucialfelix** [comment]
I'm even getting it running Deno scripts (no Next and certainly no next-image-export-optimizer).

**Comment by joshuabaker** [comment]
For posterity, I ran into this using Node 20. Switched to Node 18 and everything started working again.
