### ISSUE TITLE
Version 0.14.x broken due to '.next/static/media'

### ISSUE THREAD

**Issue by connormcwood** [Niels-IO/next-image-export-optimizer#38]
Afternoon, the latest version 0.14.0 seems to be broken with my nextjs application. 

When running on the latest version of everything I see the following issue

> Error: ENOENT: no such file or directory, stat '.next/static/media'

When running nextjs this folder does not exist within the .next output, I have no static assets as they are all dynamically imported and then ran with the tool

Looks related to this PR - https://github.com/Niels-IO/next-image-export-optimizer/pull/36/files

Let me know what you need, or want me to look into and I can come back to this issue

My next.config.js looks like this

```js
const packageVersion = require("./package.json");

const nextConfig = {
  poweredByHeader: false,
  generateBuildId: async () => {
    // You can, for example, get the latest git commit hash here
    return packageVersion.version;
  },
  async rewrites() {
    return [
      {
        source: "/:slug*.html", // Old url with .html
        destination: "/:slug*", // Redirect without .html
      },
    ];
  },
  reactStrictMode: true,
  images: {
    domains: ["localhost"],
    loader: "custom",
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920], 
  },
  env: {
    nextImageExportOptimizer_imageFolderPath: "public/images",
    nextImageExportOptimizer_exportFolderPath: "out",
    nextImageExportOptimizer_quality: 75,
    nextImageExportOptimizer_storePicturesInWEBP: true,
    nextImageExportOptimizer_generateAndUseBlurImages: true,
  },
};

module.exports = nextConfig;

```

**Comment by Niels-IO** [comment]
Hi @connormcwood,

Thank you so much for this detailed bug report! I thought of this bug but implanted the catch wrong 😄 

I published a new version where it should be resolved!

**Comment by connormcwood** [comment]
Looks like your pipeline is failing though 😁 

https://github.com/Niels-IO/next-image-export-optimizer/actions/runs/3108606388/jobs/5038167403

Looks like the E2E tests

@Niels-IO

**Comment by Niels-IO** [comment]
Hi @connormcwood,

Yes, that was quite painful to fix. Now everything should be back to normal.

**Comment by connormcwood** [comment]
Appreciate it @Niels-IO, thank you!
