### ISSUE TITLE
Uppercase extensions don't load up on safari

### ISSUE THREAD

**Issue by icy-meteor** [Niels-IO/next-image-export-optimizer#4]
I have noticed that the optimized versions have uppercase extensions like .PNG/.WEBP but these don't seem to load up on Safari for some reason. Is there any specific reason to have them in uppercase? 
<img width="943" alt="image" src="https://user-images.githubusercontent.com/22114682/156831167-dacc1027-b2a5-4c09-88aa-c4634cc3055b.png">

  "next-image-export-optimizer": "^0.6.0",

**Comment by Niels-IO** [comment]
Hi @icy-meteor,

I just tested it in Safari 15.3, and it works as expected. Could you please go to this live demo website which also run next-image-export-optimizer 0.6.0 and test it there? 
https://reactapp.dev/next-image-export-optimizer

The optimized files are stored in another folder (nextImageExportOptimizer) by default that is also used by the ExportedImage component. Maybe this is the reason?

I only choose the uppercase format to make it uniform, without any advantage over the lowercase version.

**Comment by icy-meteor** [comment]
Okay, it seems to work fine. My bad.
Closing the issue. Also thanks for this awesome package :)
