### ISSUE TITLE
ExportedImage causes Layout shift according to Lighthouse

### ISSUE THREAD

**Issue by kopino4** [Niels-IO/next-image-export-optimizer#43]
iSSUE
If I exchange the next/image Image component with ExportedImage from this package, according to Lighthouse a Layout shift occurs.

WORKAROUND
Wrapping the ExportedImage with a div with fixed size fixes this issue.

**Comment by Niels-IO** [comment]
Hi @kopino4,

Thanks for the bug report. Could you please provide an example implementation of the ExportedImage component that causes a layout shift?

**Comment by Niels-IO** [comment]
Hey @kopino4,

For statically imported images, I had to wrap the ExportedImage component in another div that gets an aspect ration style prop. So the reason can very well be what you described with a rounding error. Could you please try to test it without the aspectRatio style prop in your outer div?
Thanks

**Comment by kopino4** [comment]
Hi @Niels-IO ,

I think the issue is in the format of your aspect ratio. Look at the following situations:

WorkingOutterDiv (apect-ratio is applied to the div):

![WorkingDiv](https://user-images.githubusercontent.com/43185020/192798018-19a4347b-e6ac-45ee-802e-920d63b8ea7d.png)

BrokenOutterDiv (aspect-ratio gets ignored because of the trailing `px` at the end):

![BrokenDiv](https://user-images.githubusercontent.com/43185020/192798087-3db6b697-3f2e-420e-aa74-d4ea1e101f10.png)

**Comment by Niels-IO** [comment]
Hi @kopino4,

I have trouble reproducing your findings, unfortunately. Are you using the current version 0.14.5?

Your code here works for me without a layout shift:
```javascript
<div
        style={{
          width: '100%',
          position: 'relative',
          alignSelf: 'center',
        }}
      >
        <ExportedImage src={photo} alt="photo" layout="responsive" />
      </div>
```
Also, the aspect ratio is calculated as expected:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/47059882/193044707-3b275f84-31d4-4f2b-9aa7-c9eae449a7c2.png">

![image](https://user-images.githubusercontent.com/47059882/193045089-da5d7488-e7a4-42d2-846f-15a3084038f7.png)

**Comment by kopino4** [comment]
Hey @Niels-IO,

thanks to your answer I tried to **update** the **react** and **nextjs** version in my package.json.

This fixed the issue
