### ISSUE TITLE
Disagreement between README and actual behavior in development mode

### ISSUE THREAD

**Issue by srmagura** [Niels-IO/next-image-export-optimizer#47]
First let me say, thank you so much for this project!

The README says:

> In the development mode, the original image will be served. The optimized images are created at build time only.

But [the code](https://github.com/Niels-IO/next-image-export-optimizer/blob/e3b1a1804b3366219fc3731d7c4a942df804f52f/src/ExportedImage.tsx#L142) tries to use `optimizedLoader` regardless of whether Next is running in development mode or production mode. 

Whether the original or optimized image is rendered is determined by whether the optimized image exists in `public`.

Which is correct, the README or the code? I am happy to create a PR.

Here is a screenshot showing the problem. The image `src` is an optimized `.WEBP` file and you can tell it's development mode because of `<script>` tag for `react-refresh.js`.

![image](https://user-images.githubusercontent.com/801549/194139556-fe3d018c-8ea7-46b0-a5b0-3be8a1083ce7.png)

**Comment by Niels-IO** [comment]
Hey @srmagura,

Thanks for reporting this. It is indeed an inconsistency, and the readme is incorrect. It will only use the original src as a fallback when the next-image-export-optimizer is not yet run on the specific image. It will serve the optimized version if it finds the optimized image.

I will correct the readme. Thanks :)

**Comment by Niels-IO** [comment]
Hi @srmagura,

I hope the readme is more concise now. Let me know your thoughts.

**Comment by srmagura** [comment]
Thanks for the quick turnaround!
