### ISSUE TITLE
Requests for 10px images cause 404 errors

### ISSUE THREAD

**Issue by srmagura** [Niels-IO/next-image-export-optimizer#48]
The definition of `automaticallyCalculatedBlurDataUrl` generates a URL for a 10px image:

https://github.com/Niels-IO/next-image-export-optimizer/blob/e3b1a1804b3366219fc3731d7c4a942df804f52f/src/ExportedImage.tsx#L118-L119

But the default `imageSizes` array does not contain `10`, so you get a 404 when the browser tries to load the URL.

It seems like replacing the hardcoded `10` with the smallest number in `imageSizes` would fix this. Let me know what you think.

**Comment by Niels-IO** [comment]
Hi @srmagura,
If the env variable nextImageExportOptimizer_storePicturesInWEBP is true, then it will automatically append the with 10 to the imageSizes array. Therefore, the blurImage should be available after the next-image-export-optimizer script did run.

If the ExportedImage component should not use blurry placeholder images, one should set the prop placeholder to "none".

Does this answer the issue?

**Comment by srmagura** [comment]
Ah, I think you mean `nextImageExportOptimizer_generateAndUseBlurImages`.

I am going to submit a PR to make the README a bit more clear about how this works. Let me know if you need any other help with this library 🙂
