### ISSUE TITLE
Found 0 supported images in public/images

### ISSUE THREAD

**Issue by abhaykumar01234** [Niels-IO/next-image-export-optimizer#5]
Getting the below output. All config are as per example

```
---- next-image-export-optimizer: Begin with optimization... ---- 
Found 0 supported images in public/images
Copy optimized images...
---- next-image-export-optimizer: Done ---- 
```

**Comment by Niels-IO** [comment]
Hey @abhaykumar01234. I think the issue is the location where you execute npx next-image-export-optimizer. 
You should be in the main folder of your Next.js app. Could you please double check and if that is not working please send a picture of your file structure 🙂

**Comment by Niels-IO** [comment]
Hi @abhaykumar01234, 

I included a warning if the command was not executed in the main folder.
