### ISSUE TITLE
Custom 'onLoadingComplete' function passed is not fired

### ISSUE THREAD

**Issue by jdolinski1** [Niels-IO/next-image-export-optimizer#50]
Eventual custom 'onLoadingComplete' function passed as prop is not fired.

```
<ExportedImage
  ...
  onLoadingComplete={() =>
    console.log("This is not called.")
  } />
```

Most probably caused by this line.
https://github.com/Niels-IO/next-image-export-optimizer/blob/4dbee671faaca2fc6c804bef421e340e8cec5bfa/src/ExportedImage.tsx#L150

**Comment by Niels-IO** [comment]
Hi @jdolinski1,

Thanks for the report. The onLoadingComplete and onError callbacks will now be executed if they are present. Created #53 to fix the issue.
