### ISSUE TITLE
Potential optimization that could make builds much faster

### ISSUE THREAD

**Issue by srmagura** [Niels-IO/next-image-export-optimizer#55]
I have an image called `engagement.png` that has a width of 732px. Naturally, all of the generated images with width >= 732px are the exact same image, as evidenced by the file sizes:

![image](https://user-images.githubusercontent.com/801549/194343856-460b0295-34d7-41a8-80bc-b8ec14d8916a.png)

If I am reading the code correctly, sharp is run for each image, for each width. This means we are doing a lot of duplicate work if the image is much smaller than the max device size (3840 by default).

What if we optimized this so that the 828px, 1080px, 1200px, .etc images were created by simply copying the 750px image? (obviously this depends on the width of the original image)  

Happy to PR if you are interested.

**Comment by Niels-IO** [comment]
Hey @srmagura,

Very good idea. Yes sure, let me know if you face any issues 🙂

**Comment by Niels-IO** [comment]
Hi @srmagura,
Thanks a lot for the PR. I only added some tests to capture the behavior.
