### ISSUE TITLE
`src` does not reflect `basePath` for statically-imported images

### ISSUE THREAD

**Issue by srmagura** [Niels-IO/next-image-export-optimizer#56]
Next allows you to configure a [`basePath`](https://nextjs.org/docs/api-reference/next.config.js/basepath) so you can serve your site from a subpath. For example, we deploy our Next.js site to `www.spotvirtual.com/_preview` so we can test changes before making them live at `www.spotvirtual.com`.

I noticed that the  [`generateImageURL`](https://github.com/Niels-IO/next-image-export-optimizer/blob/29548b9dfb170d31047fbbde1bcc2371c29e043b/src/ExportedImage.tsx#L49-L55) code from `ExportedImage.tsx` does not take `basePath` into account for **statically-imported** images. Ideally, it would prepend the `basePath` since this is what `next/image` does.

It should be easy to fix. I may send a PR for this, though I am leaning towards changing our deployment so that the preview site is served from a different subdomain, e.g. `www-preview.spotvirtual.com`. This would prevent issues like this from arising in the first place.

There is a related `next.config.js` property called [`assetPrefix`](https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix). Ideally the PR for this would take `assetPrefix` into account too. If both `basePath` and `assetPrefix` are set, I'm not sure which one "wins".

**Comment by Niels-IO** [comment]
Hi @srmagura,
Thanks for the suggestion! If you like, you can propose a PR or this feature. Probably, the ExportedImage component needs to accept a further prop. I fear it might get tricky with statically imported images.

**Comment by Niels-IO** [comment]
Hi @srmagura,

Using a basepath for statically imported images works now. For images with a relative location, you can refer to the docs on how to set this up: https://nextjs.org/docs/api-reference/next.config.js/basepath#images
