### ISSUE TITLE
Types not working in new release

### ISSUE THREAD

**Issue by RichardLindhout** [Niels-IO/next-image-export-optimizer#62]
import Image from "next-image-export-optimizer/future/ExportedImage";

TS2307: Cannot find module 'next-image-export-optimizer/future/ExportedImage' or its corresponding type declarations.

**Comment by Niels-IO** [comment]
Thanks for the report. 

Somehow it was more complex than expected to get the types working for the .../future/ExportedImage component. 

It should work now in v0.17.1
