### ISSUE TITLE
Add support for next version 13

### ISSUE THREAD

**Issue by ajhawkings** [Niels-IO/next-image-export-optimizer#64]
Next.js version 13 was released yesterday - at the moment the next peer dependency is pinned at v12.x, meaning it conflicts when version 13 is installed. Can this be upgraded? The fact that next/future/image is the new default might have to be dealt with before upgrading though

**Comment by Niels-IO** [comment]
Hi @ajhawkings,

I just published version 1.0.0 and resolved the issue. Note that I follow the same breaking change as Next, which now uses the next/future/image component as default.
