### ISSUE TITLE
`placeholder="none"` leads to type error

### ISSUE THREAD

**Issue by HandyHat** [Niels-IO/next-image-export-optimizer#66]
I am trying to pass placeholder="none" as a prop but it is resulting in a type error.

![image](https://user-images.githubusercontent.com/58530748/198047427-21fe74f5-e093-45a0-acd6-d74a3514f466.png)

It looks like it is conflicting with the types for react (`@types/react`) - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/68688f3ec09c41aa8923ff232f99913e2bdb4c54/types/react/index.d.ts#L1861

**Comment by HandyHat** [comment]
Ah, thank you for the clarification! I am indeed trying to disable the placeholder, and thus will use `empty`. The readme says that `none` should be used
https://github.com/Niels-IO/next-image-export-optimizer/blob/62f1086b1714b9ec23b5dc5a5cfb40ebb9bdb16f/README.md?plain=1#L132

Perhaps it should be updated?

**Comment by Niels-IO** [comment]
Hi @HandyHat,
Oh, my bad; that should definitely be corrected. The curse of writing documentation out of memory...
