### ISSUE TITLE
v1.0.0 not working next 13

### ISSUE THREAD

**Issue by ajhawkings** [Niels-IO/next-image-export-optimizer#69]
I'm having this error below after upgrading to version 1.0.0 on next 13.0.0 with appDir enabled. Next suggests it's an issue with the package.json, but I can't figure it out... Can this be fixed? Thanks

> Error: Module not found: Package path . is not exported from package node_modules\next-image-export-optimizer (see exports field in node_modules\next-image-export-optimizer\package.json)
  2 | import Heading from '@components/heading'
  3 | 
> 4 | import ExportedImage from 'next-image-export-optimizer'
  5 | 
  6 | import styles from './Links.module.css'
  7 |

**Comment by Niels-IO** [comment]
Hey @ajhawkings,

I could reproduce the error but haven't found a fix yet. As the app directory is still in beta and, more importantly, does not support `next export`yet (https://beta.nextjs.org/docs/app-directory-roadmap#:~:text=not%2Dfound-,Planned%20Features,-The%20app%20directory), I will postpone the work to get it working. Please feel free to investigate yourself and propose a PR.

**Comment by ajhawkings** [comment]
Hi @Niels-IO, completely missed the fact that it doesn't support next export! Thanks for spending time on it.

**Comment by mdj-uk** [comment]
Hi @ajhawkings, and @Niels-IO 

I had this problem when trying to import `ExportedImage` into a server component (the default). It needs to be imported into a client component - i.e. a component with `use client` at the top of the file. After that everything works fine for me.

**Comment by mdj-uk** [comment]
As far as I'm aware `next export` isn't supported yet. When I try it I get an error about  missing `exportPathMap` in `next.config.js`. 

But in my case I just rely on automatic static optimisation and don't set up SSR or ISG or anything like that. When deployed to netlify it amounts to more or less the same thing. 

By the way, thanks for this brilliant tool. In theory I could use the next on demand optimisation in my netlify deployment, but there are so many issues, (e.g. netlify image cache not persisting after a new deploy, or randomly failing) that it's much easier to use this.

**Comment by Niels-IO** [comment]
Hi @mdj-uk,

Thanks for sharing your use case! Interesting to see that this module also can be used like this.
