### ISSUE TITLE
nextImageExportOptimizer folder leftover

### ISSUE THREAD

**Issue by vitorrloureiro** [Niels-IO/next-image-export-optimizer#70]
Hey!

First of all, thank you very much for this! 

I'm using your package for the first time and I'm facing a problem:

After I run `npm export`, next-image-export-optimizer creates a 'nextImageExportOptimizer' folder and a 'next-image-export-optimizer-hashes.json' file in my public dir.

I understand that the hashes are probably used to check if the images have already been optimized. I don't get why I get the 'nextImageExportOptimizer' leftover folder, though. In my understanding, it should be cleaned up after it's contents have been copied to the 'out' folder.

I'm I doing something wrong? Is this the expected behavior?

**Comment by Niels-IO** [comment]
Hi @vitorrloureiro,
is the nextImageExportOptimizer folder in your public directory empty, or does it contain the reduced versions of the images?

In general, it was a deliberate decision to keep the optimized images inside the nextImageExportOptimizer folder. As for the statically imported images, the output folder gets nuked by Next.js on every dev server start. 
Additionally, this behavior allows the users to check the generated images to version control if they like.

**Comment by vitorrloureiro** [comment]
Hey Niels!
Thanks for getting back.

Understood.
I wonder if it's a good decision storage wise. If you have an application with more than just a few images, having both the original and converted image can take a lot of space.

The version control argument makes sense regarding external images, but not for statically imported ones, in my opinion. I mean, if I'm creating some kind of netlify cms + nextjs project and the images are stored inside the project, I'll get both the original media and the reduced ones inside my repo, which is not necessary. Having just the originals should be enough.

Do you think it makes sense and is possible to implement some kind of functionality where users can customize this behavior (for example, selecting to completely disable this behavior or selecting to disable this behavior for statically imported images)? 

The idea would be to delete the generated nextImageExportOptimizer folder while keeping the *hashes.json (which I imagine is necessary to speed up build times).

**Comment by Niels-IO** [comment]
Hi @vitorrloureiro,

I am not sure I understand your idea fully. Maybe to summarize the behavior:

All statically imported images found in ".next/static/media" will be used for optimization and copied to "public/nextImageExportOptimizer". If I delete the folder "public/nextImageExportOptimizer" after optimization, I would have to regenerate the static images every time the script runs. 

Where would you suggest taking the optimized images from when the public/nextImageExportOptimizer is deleted?

**Comment by vitorrloureiro** [comment]
I get your point.

I thought we could get them directly from the '/out' folder, but, of course, this folder is most likely gitignored.
So yeah, I think you're right: there's no easy way around this. I guess the current behavior is indeed the most optimal one.

Sorry for wasting your time and thank you very much for your patience and support =).

**Comment by Niels-IO** [comment]
Hi @vitorrloureiro,

I think one solution for your case is to use the [rimraf](https://www.npmjs.com/package/rimraf) package to delete the folders on your own and extend the npm run export script with the rimraf command that deletes the folders you don't want to have.
