### ISSUE TITLE
Next Config imageSizes Prop Ignored?

### ISSUE THREAD

**Issue by joseph-bayer** [Niels-IO/next-image-export-optimizer#71]
Hi!

First of all, this is an incredibly useful tool - thank you for all the work you've put in!

I noticed that the `imageSizes` property setting in my next.config are being ignored during the `next-image-export-optimizer` process.

Here is what `next-image-export-optimizer` is showing:
![image](https://user-images.githubusercontent.com/49461754/200136895-11454c77-c692-4f6b-90b2-7745ae9cfd3d.png)

Here's what my `next.config.js` file looks like:
```
module.exports = {
  images: {
    loader: "custom",
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
  },
  trailingSlash: true,
  env: {
    nextImageExportOptimizer_imageFolderPath: "public/pokemon-images",
    nextImageExportOptimizer_exportFolderPath: "out",
    nextImageExportOptimizer_quality: 75,
    nextImageExportOptimizer_storePicturesInWEBP: "true",

    // If you do not want to use blurry placeholder images, then you can set
    // nextImageExportOptimizer_generateAndUseBlurImages to false and pass
    // `placeholder="none"` to all <ExportedImage> components.
    //
    // If nextImageExportOptimizer_generateAndUseBlurImages is false and you
    // forget to set `placeholder="none"`, you'll see 404 errors for the missing
    // placeholder images in the console.
    nextImageExportOptimizer_generateAndUseBlurImages: true,
  },
  experimental: {
    workerThreads: false,
    cpus: 1,
  },
};
```

And here are the two instances of `ExportedImage` in my app:
```
<ExportedImage
  src={`/type_svgs/${type.name.toLowerCase()}.svg`}
  alt={`${type.name} Type icon`}
  width={25}
  height={25}
  placeholder={"empty"}
/>
```
```
<ExportedImage
  src={`/pokemon-images/${pokemonData.pokemonApiName}.png`}
  alt={`Picture of the Pokemon ${pokemonData.name}`}
  width="350"
  height="350"
  useWebp={process.env.nextImageExportOptimizer_storePicturesInWEBP === "true"}
  priority
/>
```

**Comment by Niels-IO** [comment]
Hi @joseph-bayer,

Thank you very much for your nice words!

I am sorry but I cannot spot where the imageSizes are not reflected. The numbers in the CLI output seems to be the ones in the next.config. 

Could you help me understand?

**Comment by joseph-bayer** [comment]
@Niels-IO 
Oh wait… is it exporting images for all the numbers in both the imageSizes and deviceSizes arrays? I assumed it was just pulling the sizes from the imageSizes array. Because of that assumption, I thought the next-image-export-optimizer process was creating more images than necessary.

**Comment by joseph-bayer** [comment]
@Niels-IO - I just checked the optimization code and realized that it’s pulling the image sizes from both the imageSizes and deviceSizes arrays (and also cleverly generating a 10px image to use for the placeholder).

It looks like everything is working correctly. Thanks again for all the work you’ve put into this!! 😄

**Comment by Niels-IO** [comment]
Hi @joseph-bayer,

No worries! I kept the same logic as Next.js and they use also two arrays which then together form the array of sizes. 

I am happy that the library is useful!
