### ISSUE TITLE
Query parameters confuse the replacement with optimized images

### ISSUE THREAD

**Issue by wbern** [Niels-IO/next-image-export-optimizer#77]
I use notion which has expiration dates on all files fetched through its API.

The URL's look something like the following:

```
[hash]/image.png?X-Amz-Algorithm=...&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=...%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=....&X-Amz-Expires=3600&X-Amz-Signature=...&X-Amz-SignedHeaders=host&x-id=GetObject
```

It took me some time to realize that while these images are downloaded just fine, they aren't being replaced on the site.

Removing the query parameter from the requests fixes this, but it would be nice if this tool could handle it (or mention it in the readme) to avoid unnecessary pitfalls for others.

Thanks for a great project.

**Comment by Niels-IO** [comment]
Hi @wbern,

I am afraid I don't understand the use case clearly yet. 
Could you please describe the mechanism in more detail? At the export time, are the images downloaded from the Notion API? Or are they still referenced by the URL?

What do you mean by that they aren't replaced on the site?

I only tested and coded the module for local images and not (yet) remote images (This is stated in the documentation already)

**Comment by Niels-IO** [comment]
Hi @wbern,

Just wanted to check in and see if you've had a chance to add any more information to this issue. Any extra details would be helpful in getting this figured out. 

Thanks in advance for your help.

**Comment by wbern** [comment]
Hey!

I think I had misunderstood that remote images weren't supported. 🙂 So maybe my issue is moot

**Comment by Niels-IO** [comment]
Cool, thanks for the answer. Honestly, I have never tested any remote images with the tool. I will close this issue for now.
