### ISSUE TITLE
Optimized images not found because theyre not in root

### ISSUE THREAD

**Issue by kevincarld** [Niels-IO/next-image-export-optimizer#78]
Hi,
Im using next export and the images are not found, How do I make it such that the beginning path of images has "./" instead of "/".

Thanks

**Comment by Niels-IO** [comment]
Hi @kevincarld,

Could you please explain the use case of "./" instead of "/" to me? Can you share an example of how you are using the ExportedImage component?

**Comment by kevincarld** [comment]
Hi @Niels-IO , actually I think I just have the same issue as the other comments. Because the static site im exporting won't be in the root directory that's why image src's are having issue

**Comment by Rashair** [comment]
Can this be reopened? My images are not found after proper export:

Code:
```
  import logo from "public/images/logo.png";
...
 <ExportedImage src={logo} style={{height: "100%", width: "auto"}}
                             alt="Faces in front of each other"/>
```


```
package.json
"build:docker": "next build && next export -o .export && next-image-export-optimizer --exportFolderPath .export",

DockerFile:
WORKDIR /app/clientApp
COPY --from=builder /opt/app/.export ./
```
Container:
![image](https://user-images.githubusercontent.com/33404585/206932165-abbb2a41-a960-4e56-ae41-6618fa0d68cd.png)

The app: 
![image](https://user-images.githubusercontent.com/33404585/206932198-8ab278ca-9b05-4fa0-bcb5-34b3e28529f3.png)
![image](https://user-images.githubusercontent.com/33404585/206932235-444fdf56-2051-4146-9359-443025bbf25f.png)




It seems like the path should be under `images`?

**Comment by Rashair** [comment]
Actually:
logo-opt-10.WEBP

**Comment by Rashair** [comment]
It seems like the images are incorrectly stored under `images` directory instead of `nextImageExportOptimizer`

**Comment by Rashair** [comment]
There only under 'images' - nowhere else. The nextImageExportOptimizer folder does not appear. I've also tried on your example app and it works locally for me there, but not in my own app :/

**Comment by Rashair** [comment]
I think the issue is with the statically imported images - other seem to work

**Comment by Niels-IO** [comment]
Hi @Rashair,

I am currently a little bit clueless about how to help you further. Could you create a minimal example that reproduces the error?

**Comment by Rashair** [comment]
I think I found the issue - I have a custom `distDir`, it's `.build`, not `.next`.
Here's a reproduction using your example:
https://github.com/Rashair/next-image-export-optimizer-78
(It only works on the clean repo - if you don't have .next dir there, otherwise it will supposedly copied from there)

**Comment by Niels-IO** [comment]
Hi @Rashair,

Thank you very much! This is indeed the issue, and I found an easy fix. I will release it in the next patch version.
