### ISSUE TITLE
Image Quality on per image base

### ISSUE THREAD

**Issue by Fritze1602** [Niels-IO/next-image-export-optimizer#79]
Hi, first of all thank you for your amazing library and the perfect docs.
I have a feature request. I would love to have the image quality as a an (optional) prop on <ExportedImage quality="94" />. I wonderf if this would be possible.
Many thanks in advance and kind regards

**Comment by Niels-IO** [comment]
Hi @Fritze1602

Thank you very much for your kind words. 
It wouldn't be possible to pass the quality as a prop as the module does not look at the code base. It only takes the images from the image folder and uses them to do the image resizing operation. 

The only way that I could think this would be possible, if the hash file stores the requested quality as an argument per image. At first this would be the default and then you could change it here. 

I don't think this would be a particular elegant solution though. 

Can I ask why you want to steer the quality prop on a per image basis?

**Comment by Niels-IO** [comment]
Hi @Fritze1602 

Thanks for the explanation! I understand your point. 
I will put this feature on the backburner. Maybe I have a better idea on how to do it in the future. 

Cheers
Niels

**Comment by Fritze1602** [comment]
Thanks a million for this and your thoughts about it. I hope I will increase my abilities in next js and your fantastic library in the nearer future, so I hopefully come up with a few ideas too. At the moment I am simply not good enough... .
