### ISSUE TITLE
allow image export to remote edge server

### ISSUE THREAD

**Issue by augustblack** [Niels-IO/next-image-export-optimizer#83]
Hi,

First, thanks for making this project. 

I have a use case where I am trying to host the next-exported files (html, js, css, etc) separately from the images.   I'd like to host the images on a remote edge server (eg, S3 or similar) and was wondering if there might be a way to:

1. make it so the next-image-export-optimizer renders all versions of the static images into one folder.  That might be happening already, but it seems like there are duplicate nextImageExportOptimize folders that may be copied from the /public build
2. allow the substitution of all image sources with a remote URL (eg. replace source images '/nextImageExportOptimizer' with 'https://myedgeserver/path/to/file'

I've tried doing a simple `find | sed` on the output, but it's not clear to me if the source sets are even being used.

I guess my questions are:

- How to test if the source sets are being used?  I can't see in the browser.  It appears as if '_next/static/path/to/full/file' is being used instead of 'nextImageExportOptimize' ones
- How would you go about doing the above?  Do you reckon a string replace work on the output?  
- Is there maybe a better way?

thanks for any input you might have and for this great project.

**Comment by Niels-IO** [comment]
> First, it appears with a simple export, the blur images are not getting used. The images load with a blank first and then come in with the full image (even though placeholder="blur" is set and was working in the past versions).

Are you using Firefox? Blurry placeholders currently do not work in Firefox, unfortunately. The background image does not get displayed.

> Second, it seems as if the first url that is loaded is /_next/static/media/<filename> and not /nextImageExportOptimizer/<filename>

This is only the case when the optimized images cannot be found, and the /_next/static/media/<filename> is then used as a fallback. Could you please check whether the folder nextImageExportOptimizer was generated in your public folder and contains the optimized images?

> Third, when I run a simple static html server (eg. python3 -m http.server) on the exported output, it seems as if either this module or next.js (not sure which) is prepending a full http://hostname:port to the URL - instead of src="/filename" it is setting src="http://localhost:8000/filename" Ideally, the image src would only have a relative path to the hostname and not include the hostname in the URL.

This is not done purposely by this module. I guess that it is also happening in the standard Next.js image component.

> Do you happen to know why /_next/static/media/<filename> is created at all?

This is where Next.js stores the optimized statically imported images.

**Comment by augustblack** [comment]
Hi, 

I'm not using firefox and was having issues with the blur in chrome.

The nextImageExportOptimizer folder was created and all the files are there.

Ultimately, I did a little digging and decided to use the base Image module of next but set a custom loader.
That doesn't auto-generate the images like this module does, but was more straightforward for my use case.

thanks for the attention and for this software - I still use it in other cases.
