### ISSUE TITLE
Issue with fallback src inside nested slug 

### ISSUE THREAD

**Issue by lucianamendez** [Niels-IO/next-image-export-optimizer#84]
Hi :) 

First, thanks for this project! So far is working great, but I think there could be a minor issue with unoptimized fallbacks and slugs. 
I just tried to implement it on a static blog based on this [Next starter](https://github.com/vercel/next.js/tree/canary/examples/blog-starter) folder structure. So, the slug is inside of a posts folder resulting in a url like this: **"localhost:3000/posts/:slug"**. The image component I created works flawless everywhere except on the post page itself because for some reason it's adding "posts" from the folder name to the src path throwing 404. This is only happening on the local images when the slug is nested in a folder instead of the main page level like: **"localhost:3000/:slug"** . Probably it's the base path in a condition or something like that. After running the optimizer everything works fine since it's not affecting the final webp files path. 

Let me know if you have any trouble trying to reproduce it. Thankss!

![fallback](https://user-images.githubusercontent.com/30813805/207507072-59465f97-7993-4ff8-bef1-b7c2a3cecb06.png)

**Comment by Niels-IO** [comment]
Hi @lucianamendez,
Thank you very much for the bug report. I was able to reproduce and fix the issue. I will publish the fix soon!
