### ISSUE TITLE
Lowest quality images are used in the dev mode

### ISSUE THREAD

**Issue by Rashair** [Niels-IO/next-image-export-optimizer#87]
Although the optimisation seem to work in the exported mode, the correct image quality is not loaded in the dev mode.

![image](https://user-images.githubusercontent.com/33404585/208299549-51b2156b-f48f-4ff3-b094-810eedfd7948.png)

The correct image size seems to be loaded though
![image](https://user-images.githubusercontent.com/33404585/208299588-b44fb623-19e6-4f4f-a011-2b17ead51354.png)

The problem disappears when I delete the local optimised folders / disable the background property.
It seems like the background overlays the image.

**Comment by Niels-IO** [comment]
Could you please explain in more detail why you concluded that the correct image size is not loaded?

**Comment by Rashair** [comment]
Because I see it - it's blurred. I'm not sure if the if it's indeed that the correct image size is not loaded or the blur is somehow overlapping the real picture, because when I disable the background via browser console it's being displayed clearly.

**Comment by Niels-IO** [comment]
Hi @Rashair,

I think I found the issue. Could you please update to the latest version and check if everything works as expected now?

**Comment by Rashair** [comment]
Hi :) Yes, it works now (v.1.1.2) - I don't see any difference in dev and exported mode 🙇🏻‍♂️ 
Thank you, you're doing a great job with this lib 💪🏻
