### ISSUE TITLE
Typescript Types?!

### ISSUE THREAD

**Issue by lgn-lvx3** [Niels-IO/next-image-export-optimizer#9]
Hey, really appreciate this library!

I'm using typescript and I was wondering if it would be easy to add them myself or add them to the resource here @types/next-image-export-optimizer

Any input appreciated! 

Again thank you for this library, I think its a problem that next doesn't allow image exporting with using their image component.

**Comment by Niels-IO** [comment]
Hey @lgn-lvx3,
I rewrote the ExportedImage component in Typescript. Please check it out in v 0.9.3

Let me know if everything works as expected.

**Comment by lgn-lvx3** [comment]
Hell yeah @Niels-IO , I'll update and try it out!

**Comment by Niels-IO** [comment]
Hey @lgn-lvx3,
did you have a chance to try the TypeScript implementation?

**Comment by lgn-lvx3** [comment]
I haven’t, fires being put out, you know the deal 🔥

I will ASAP and get back to you.

**Comment by lgn-lvx3** [comment]
Works like a champ @Niels-IO, thanks for quick update and library! I'll stay tuned and let you know if I have any issues. Still working on converting everything to be statically exported but at least I can export now!
