### ISSUE TITLE
Support multiple extensions

### ISSUE THREAD

**Issue by NiedziolkaMichal** [Niels-IO/next-image-export-optimizer#90]
I think this library would be a lot better if we could choose to generate images in multiple extensions and let the browser choose the format that it supports.
Currently, either original extension of an image is used, but when a condition is met, it can be changed to WebP. Native NextJS image loader will detect support for an image format and serve the image in the best possible format to a user. This can be replicated, by usage of `picture` element:
```html
<picture>
    <source srcset="path.AVIF 1x, path.AVIF 2x" type="image/avif">
    <source srcset="path.WEBP 1x, path.WEBP 2x" type="image/webp">
    <img srcset="path.JPG 1x, path.WEBP 2x" src="path.JPG" width="200" height="112.5">
</picture>
```

**Comment by Niels-IO** [comment]
Hi @NiedziolkaMichal,

It would be nice, but the way the library operates is incompatible with the suggestion. 

I use the implementation of Next.js' original image component as much as possible and would have to move to a complete custom version of it to support the suggested approach.
Currently, the WEBP support is excellent across browsers (https://caniuse.com/webp), with 97% coverage.
