### ISSUE TITLE
Vague error message

### ISSUE THREAD

**Issue by CaptainN** [Niels-IO/next-image-export-optimizer#92]
The plugin failed with an error:

```
[Error: Input buffer contains unsupported image format]
```

A better error message might include the path or some kind of information about the image, so it can be tracked down more easily.

**Comment by CaptainN** [comment]
I think the problem is that it's trying to load external images from a local cache? I get these very strange URL errors in my console when running in dev mode:

```
GET http://localhost:3000/https:/storage.googleapis.com/assets/nextImageExportOptimizer/on-of-my-images.WEBP 404 (Not Found)
```

The images URLs log out just fine (with 2 slashes, without the prefix).

Does this not support external images?

**Comment by CaptainN** [comment]
Unfortunately that didn't work (still tries to optimize images).

```
---- next-image-export-optimizer: Begin with optimization... ---- 
info  - Loaded env from /Users/kevin.newman/repos/project/.env.production.local
Found 35 supported images in public/images, static folder and subdirectories.
Using sizes: 10,16,32,48,64,96,128,256,384,640,750,828,1080,1200,1920,2048,3840
Start optimization of 35 images with 17 sizes resulting in 595 optimized images...
███████████████ 38% | ETA: 5s | 230/595 | Total size: 2.6 MBnode:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Input buffer contains unsupported image format]
```

I'm going to try and preload them myself, and then link them up from the local directory.

Thanks for the work on this package. It is appreciated.

**Comment by Niels-IO** [comment]
Hi @CaptainN,

You could make remote images work with the standard Next.js image component like this (without any optimization)

```javascript
import Image from "next/image";

 <Image src="https://reactapp.dev/images/nextImageExportOptimizer/BG_HERO-opt-2048.WEBP"
unoptimized
loader={({ src }) => {
     return src;
}}
alt={"test_image"}
/>
```

**Comment by CaptainN** [comment]
The images all come from a CMS, and stored in an s3 bucket. I think the issue is that something was causing my own app domain to be prepended to the image bucket domain, breaking the links. The package was likely receiving garbage or a 404 page from next.

**Comment by Niels-IO** [comment]
I added the error message that spits out the problematic file name.
