### ISSUE TITLE
nextImageExportOptimizer_exportFolderPath duplicated

### ISSUE THREAD

**Issue by GuerrillaCoder** [Niels-IO/next-image-export-optimizer#94]
In example config `nextImageExportOptimizer_exportFolderPath` is duplicated with different value.  Is it supposed to be 2 different keys?

**Comment by Niels-IO** [comment]
Hi @GuerrillaCoder,

Thank you very much for making me aware. It is a typo that and I corrected it now!

The variable nextImageExportOptimizer_exportFolderName can be used to rename the export folder name and therefore also the generated srcset URLs. 

Thanks,
Niels
