### ISSUE TITLE
Animated Images Support

### ISSUE THREAD

**Issue by dli7319** [Niels-IO/next-image-export-optimizer#95]
Currently, animated images (WebP, GIF) are turned into static images.

Based on https://sharp.pixelplumbing.com/api-constructor, it looks like animated images support could be enabled by simply adding `{ animated: true }` to https://github.com/Niels-IO/next-image-export-optimizer/blob/ddb110c2b0715996fd67a6ac7d731927cf4e7a20/src/optimizeImages.js#L417

It would be awesome if this functionality could be exposed through an environment variable.

Note that next/image [claims to bypass animated images](https://nextjs.org/docs/api-reference/next/image#animated-images).

**Comment by david-zacharias** [comment]
Decision could also be made based on the source image extension (as read in [L331](https://github.com/Niels-IO/next-image-export-optimizer/blob/ddb110c2b0715996fd67a6ac7d731927cf4e7a20/src/optimizeImages.js#L331)) , to set `{animated: true }` for webP, GIF only

**Comment by dli7319** [comment]
Thanks for the example of using unoptimized.

In my own experiments, adding animated to your code seems to work perfectly, albeit with very slow performance:
https://github.com/dli7319/next-image-export-optimizer/commit/8741983c1345a1000a70fc5e12a155a12b699916
The 67.4 MB GIF gets converted properly into smaller animated WebP images
![image](https://user-images.githubusercontent.com/27523415/218132376-e95382be-9405-44f8-914b-ca47b5ee2478.png)
E.g. [720p_gif-opt-750.WEBP](https://raw.githubusercontent.com/dli7319/next-image-export-optimizer/8741983c1345a1000a70fc5e12a155a12b699916/out/images/nextImageExportOptimizer/720p_gif-opt-750.WEBP)

Nevertheless, it would also be nice if unoptimized could be automatically applied for animated images like in next.js in case someone doesn't want animated images to be optimized:
https://github.com/vercel/next.js/blob/1c5983fe95b79cc9ea1e52d19e69adf7827eda5a/packages/next/src/server/image-optimizer.ts#L589

**Comment by Niels-IO** [comment]
Interesting that it works for you. When I only change this line in the code

 const transformer = sharp(imageBuffer, { animated: true });

the generated image is not animated anymore. Did you do something else that I am missing?

Regarding your second point: The unfortunate thing is that the isAnimated package is a server package and on the client side where I would need to set the unoptimized prop, we cannot run such a check.

**Comment by dli7319** [comment]
I put all the changes I made in that commit and just ran `optimize_gif.sh` so I have no idea why it wouldn't work for you as well.
Sharp is installed from `npm ci` so it should match the version in your `package-lock.json`. 
FWIW, I'm testing on Ubuntu 22.04.

**Comment by dli7319** [comment]
I just tested using your static noise gif and animated png (https://github.com/dli7319/next-image-export-optimizer/commit/39af8a663e0b14960296c07c2cbdfd15691c4c13).
The noise GIF works: https://raw.githubusercontent.com/dli7319/next-image-export-optimizer/39af8a663e0b14960296c07c2cbdfd15691c4c13/public/images/nextImageExportOptimizer/402107790_STATIC_NOISE-opt-256.WEBP
The animated PNG becomes static: https://raw.githubusercontent.com/dli7319/next-image-export-optimizer/39af8a663e0b14960296c07c2cbdfd15691c4c13/public/images/nextImageExportOptimizer/animated-opt-256.WEBP

**Comment by Niels-IO** [comment]
Thanks, I just came to the same conclusion. I was irritated as the webp version did not animate in the file preview, but they do in the browser.
Also, the WEBP animated image works. The issue with the apng seems to be described here: https://github.com/lovell/sharp/issues/2375
