### ISSUE TITLE
Export script order

### ISSUE THREAD

**Issue by PeterKottas** [Niels-IO/next-image-export-optimizer#96]
Hi, just a quick question. When you say:
```
{
-  "export": "next build && next export",
+  "export": "next build && next export && next-image-export-optimizer"
}
```
Shouldn't the order actually be
```
{
-  "export": "next build && next export",
+  "export": "next build && next-image-export-optimizer && next export"
}
```
So that it first generates the images and then puts them into the appropriate folder? Or am I missing something? Thanks!

**Comment by Niels-IO** [comment]
Hi @PeterKottas,
The order in the README is correct, as the command "next export" empties the build directory each time it runs. So only after the exported files are put into the build folder can we populate the exported image into this folder.

**Comment by PeterKottas** [comment]
Gotcha! It was acting out cause it couldn't find the images path and I didn't notice the error. That's what was throwing me off. You're right, all is good, thanks!
