### ISSUE TITLE
Handling non-local image sources

### ISSUE THREAD

**Issue by wpoynter** [Niels-IO/next-image-export-optimizer#99]
First of all, thank you for your package, I find it very helpful.

I have run into an issue where it does not deal well with a new blog I am managing. The content is curated with a headless Ghost and then the Next.JS site is built and exported to creates a static site. I found that in our index page where I pass the URL of the featured image directly to ExportedImage directly caused issues unless I used the flag "unoptimized".

I entirely see why. But I was thinking it would be great if this package could pull/download the image at build time and create optimised versions to be used just like a locally referenced version. If this is already possible and I have set things up wrongly, please let me know. If this is not possible, I am willing to do the coding work to make this possible.

My end goal is to have a headless CMS that when a none engineering user edits a post the site is rebuilt in automation and it creates a static website with as much optimisation as reasonable/sensible. 

The index page for reference: https://wordcloudplus.com/blog/

I wanted to check in before embarking on potentially unneeded development.

**Comment by Niels-IO** [comment]
Hi @wpoynter,

Thank you very much for your kind words!

At the moment you can only use the remote images in an unoptimised fashion as you are currently using. 

I have an idea on how to make it work with remote images. I am currently experimenting and will update you on the progress. 🙂

**Comment by Niels-IO** [comment]
I have created an initial concept for remote images in #101 
I have to test it more and write some test but it is looking promising

**Comment by wpoynter** [comment]
Sorry for the slow response on this, I have yet to test the work, but thank you for taking a crack at it. I expect I will get to test it within the next week or two.
